import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "fr" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("nova-visio-lang");
    if (saved === "en" || saved === "fr") return saved;
    // Detect browser language
    const browserLang = navigator.language.toLowerCase();
    return browserLang.startsWith("en") ? "en" : "fr";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("nova-visio-lang", lang);
    document.documentElement.lang = lang;
  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    const translations = language === "fr" ? fr : en;
    return (translations as Record<string, string>)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
}

// ─── FRENCH TRANSLATIONS ───────────────────────────────────────
const fr: Record<string, string> = {
  // ── Navbar ──
  "nav.home": "Accueil",
  "nav.services": "Services",
  "nav.services.web": "Site web",
  "nav.services.brand": "Logo & identité visuelle",
  "nav.pricing": "Tarifs",
  "nav.referral": "Recommandation",
  "nav.blog": "Blog",
  "nav.about": "À propos",
  "nav.contact": "Contact",
  "nav.cta": "Parlons de votre projet",

  // ── Hero ──
  "hero.badge": "Made in Switzerland · Artisans, indépendants & PME",
  "hero.title.line1": "Votre talent mérite",
  "hero.title.highlight": "d'être vu.",
  "hero.subtitle": "Site vitrine, landing page, identité visuelle.",
  "hero.subtitle2": "Les outils pour être vu, compris",
  "hero.subtitle3": "et contacté. Dès",
  "hero.subtitle.price": "900 CHF",
  "hero.cta.primary": "Réserver un appel gratuit",
  "hero.cta.secondary": "Découvrir nos services",

  // ── Services Section (Home) ──
  "services.title.line1": "Deux expertises.",
  "services.title.highlight": "Un seul objectif.",
  "services.subtitle.1": "Être vu",
  "services.subtitle.2": "Être compris",
  "services.subtitle.3": "Être choisi",
  "services.web.title": "Site vitrine et landing page",
  "services.web.description": "Vos prospects arrivent, comprennent votre offre en 5 secondes et vous contactent. C'est ça, un bon site.",
  "services.web.cta": "Découvrir nos créations web →",
  "services.web.price": "dès 900 CHF",
  "services.brand.title": "Identité visuelle & logo",
  "services.brand.description": "Fini le logo fait sur Canva. Une vraie identité qui vous démarque et que vous pouvez utiliser partout.",
  "services.brand.cta": "Voir nos identités visuelles →",
  "services.brand.price": "dès 900 CHF",
  "services.badge": "POUR : ARTISANS, PME, FREELANCES, STARTUP",

  // ── Web Benefits ──
  "services.web.b1": "Gagnez en crédibilité",
  "services.web.b1h": "dès les premières secondes",
  "services.web.b2": "Convertissez vos visiteurs",
  "services.web.b2h": "en clients qualifiés",
  "services.web.b3": "Présentez vos offres",
  "services.web.b3h": "avec clarté et impact",
  "services.web.b4": "Soyez visible sur Google",
  "services.web.b4h": "grâce au référencement naturel",
  "services.web.b5": "Un site rapide et fluide",
  "services.web.b5h": "sur mobile comme sur ordinateur",

  // ── Brand Benefits ──
  "services.brand.b1": "Soyez reconnu",
  "services.brand.b1h": "au premier coup d'œil",
  "services.brand.b2": "Inspirez confiance",
  "services.brand.b2h": "avant même de parler",
  "services.brand.b3": "Une image cohérente",
  "services.brand.b3h": "sur tous vos supports",
  "services.brand.b4": "Démarquez-vous",
  "services.brand.b4h": "de vos concurrents",
  "services.brand.b5": "Un logo professionnel",
  "services.brand.b5h": "déclinable partout",
  "services.brand.b6": "Une charte graphique",
  "services.brand.b6h": "simple à appliquer",

  // ── Maintenance Section (Home) ──
  "maintenance.badge": "🔄 Suivi continu",
  "maintenance.title.1": "Livré.",
  "maintenance.title.2": "Puis suivi.",
  "maintenance.subtitle": "performances, modifications.",
  "maintenance.subtitle.bold1": "Mises à jour",
  "maintenance.subtitle.bold2": "travailler pour vous",

  // ── Maintenance Card ──
  "maintenance.card.bestseller": "⭐ Best-seller",
  "maintenance.card.title": "Suivi & Maintenance",
  "maintenance.card.subtitle": "Votre site reste performant, sans effort de votre part.",
  "maintenance.card.from": "dès",
  "maintenance.card.price": "89 CHF/mois",
  "maintenance.card.nocommit": "Sans engagement - résiliable à tout moment",
  "maintenance.card.f1": "Hébergement & nom de domaine",
  "maintenance.card.f1h": "géré",
  "maintenance.card.f2": "Mises à jour techniques",
  "maintenance.card.f2h": "& sécurité",
  "maintenance.card.f3": "Sauvegardes automatiques",
  "maintenance.card.f3h": "hebdomadaires",
  "maintenance.card.f4": "1h de modifications",
  "maintenance.card.f4h": "de contenu par mois",
  "maintenance.card.f5": "Rapport mensuel de performance",
  "maintenance.card.f5h": "(visites, contacts)",
  "maintenance.card.f6": "Support réactif",
  "maintenance.card.f6h": "sous 48h",
  "maintenance.card.cta": "Activer le suivi",
  "maintenance.card.included": "Inclus automatiquement à la fin de chaque projet.",

  // ── Benefits Section (Home) ──
  "benefits.title.1": "Ce que ça change.",
  "benefits.title.2": "Concrètement.",
  "benefits.subtitle": "Quand votre image et votre site",
  "benefits.subtitle2": "font enfin le job.",
  "benefits.b1.text": "Vos clients comprennent ",
  "benefits.b1.highlight": "en quelques secondes",
  "benefits.b1.rest": " ce que vous faites - plus besoin d'expliquer 10 fois.",
  "benefits.b2.text": "Vous avez une ",
  "benefits.b2.highlight": "image pro et cohérente",
  "benefits.b2.rest": " sur tous vos supports, sans y passer vos soirées.",
  "benefits.b3.text": "Vous ",
  "benefits.b3.highlight": "attirez les bons clients",
  "benefits.b3.rest": " - ceux qui comprennent votre valeur et ne négocient pas vos prix.",
  "benefits.b4.text": "Votre ",
  "benefits.b4.highlight": "charge mentale digitale diminue",
  "benefits.b4.rest": " : tout est en place, vous pouvez bosser sur votre métier.",

  // ── Why Us Section ──
  "whyus.badge": "Notre différence",
  "whyus.title.1": "NOVA VISIO.",
  "whyus.title.highlight": "La différence.",
  "whyus.r1.title": "Zéro jargon",
  "whyus.r1.desc": "On parle comme des humains. Pas de \"synergie UX\" ni de \"paradigme digital\".",
  "whyus.r2.title": "Un vrai\naccompagnement",
  "whyus.r2.desc": "On ne vous lâche pas après la livraison. On reste là tant que vous avez besoin.",
  "whyus.r3.title": "Qualité > quantité",
  "whyus.r3.desc": "On prend peu de projets à la fois. Chacun a notre attention complète.",
  "whyus.r4.title": "Résultats,\npas promesses",
  "whyus.r4.desc": "On ne vend pas du rêve. On construit des outils qui travaillent pour vous.",

  // ── Steps Section (Home) ──
  "steps.title": "5 étapes.",
  "steps.title.highlight": "Zéro flou.",
  "steps.subtitle.bold1": "simple",
  "steps.subtitle.bold2": "transparent",
  "steps.subtitle.rest": "du début à la fin.",
  "steps.s1.title": "On échange",
  "steps.s1.subtitle": "15 min",
  "steps.s1.desc": "Un appel gratuit pour comprendre votre activité, vos objectifs et ce qui bloque aujourd'hui.",
  "steps.s2.title": "On diagnostique",
  "steps.s2.subtitle": "votre situation",
  "steps.s2.desc": "On analyse ce qui existe - site, image, messages - et on identifie ce qui doit changer.",
  "steps.s3.title": "On construit",
  "steps.s3.subtitle": "les fondations",
  "steps.s3.desc": "Positionnement, identité visuelle, structure des messages. Les bases solides avant le design.",
  "steps.s4.title": "On crée",
  "steps.s4.subtitle": "votre site",
  "steps.s4.desc": "Design sur mesure, pages structurées pour convaincre, expérience fluide sur tous les écrans.",
  "steps.s5.title": "On lance",
  "steps.s5.subtitle": "& on suit",
  "steps.s5.desc": "Mise en ligne, formation rapide, et suivi mensuel pour que votre site reste un outil efficace.",
  "steps.bottom": "Processus transparent et collaboratif",

  // ── CTA Section (Home) ──
  "cta.title.1": "15 minutes.",
  "cta.title.highlight": "Sans engagement.",
  "cta.subtitle.1": "On fait le point sur",
  "cta.subtitle.bold1": "votre situation",
  "cta.subtitle.2": "On vous dit",
  "cta.subtitle.bold2": "franchement",
  "cta.subtitle.3": "si on peut vous aider.",
  "cta.primary": "Réserver un appel gratuit →",
  "cta.secondary": "Voir nos tarifs →",

  // ── Referral CTA ──
  "referral.title.1": "Recommandez Nova Visio.",
  "referral.title.highlight": "Gagnez 100 €.",
  "referral.subtitle.1": "Un proche lance son activité ?",
  "referral.subtitle.bold1": "Parlez-lui de nous",
  "referral.subtitle.2": "S'il signe un site web, vous recevez",
  "referral.subtitle.bold2": "100 €",
  "referral.cta": "Découvrir le programme →",

  // ── Blog Section (Home) ──
  "blog.title.1": "On partage. On",
  "blog.title.highlight": "éclaire.",
  "blog.subtitle.bold1": "concrets",
  "blog.subtitle.1": "sur votre site,",
  "blog.subtitle.bold2": "présence en ligne",
  "blog.subtitle.2": "votre image et votre",
  "blog.readArticle": "Lire l'article",
  "blog.viewAll": "Voir tous les articles",

  // ── Footer ──
  "footer.rights": "Tous droits réservés.",

  // ── Contact Page ──
  "contact.title.1": "Parlons-en.",
  "contact.title.highlight": "15 minutes.",
  "contact.subtitle.bold1": "votre situation",
  "contact.subtitle.1": "On fait le point sur",
  "contact.subtitle.2": "Pas de pitch commercial.",
  "contact.subtitle.bold2": "conversation honnête",
  "contact.subtitle.3": "Juste une",
  "contact.form.firstName": "Prénom",
  "contact.form.firstName.placeholder": "Votre prénom",
  "contact.form.lastName": "Nom",
  "contact.form.lastName.placeholder": "Votre nom",
  "contact.form.email": "Email",
  "contact.form.email.placeholder": "votre@email.com",
  "contact.form.projectType": "Type de projet",
  "contact.form.projectType.placeholder": "Sélectionnez un type de projet",
  "contact.form.projectType.call": "Appel découverte gratuit (15 min)",
  "contact.form.projectType.website": "Site vitrine",
  "contact.form.projectType.landing": "Landing page",
  "contact.form.projectType.brand": "Identité visuelle & logo",
  "contact.form.projectType.packDigital": "Pack Digital & Branding",
  "contact.form.projectType.packRefonte": "Pack Refonte Globale",
  "contact.form.projectType.maintenance": "Suivi & Maintenance",
  "contact.form.projectType.other": "Autre / Question",
  "contact.form.message": "Message",
  "contact.form.message.placeholder": "Décrivez votre projet et vos objectifs...",
  "contact.form.submit": "Envoyer ma demande",
  "contact.form.submitting": "Envoi en cours...",
  "contact.form.reassurance": "✓ Réponse sous 24h   ✓ Sans engagement   ✓ Appel en français",
  "contact.form.success.title": "Message envoyé !",
  "contact.form.success.desc": "Nous vous répondrons sous 24 à 48 heures.",
  "contact.form.error.title": "Erreur",
  "contact.form.error.desc": "Une erreur est survenue. Veuillez réessayer.",
  "contact.form.validation.title": "Erreur de validation",
  "contact.form.validation.desc": "Veuillez corriger les erreurs du formulaire.",
  "contact.whatNext.fast.title": "Réponse rapide",
  "contact.whatNext.fast.desc": "Nous vous répondrons sous 24 à 48 heures.",
  "contact.whatNext.noPressure.title": "Sans pression",
  "contact.whatNext.noPressure.item1": "Discussion constructive",
  "contact.whatNext.noPressure.item2": "Solutions adaptées",
  "contact.booking.title": "Ou réservez directement un",
  "contact.booking.highlight": "créneau",

  // ── About Page ──
  "about.title": "Qui sommes-",
  "about.title.highlight": "nous.",
  "about.subtitle": "Trop d'entrepreneurs méritent mieux",
  "about.subtitle2": "qu'un site sur un template générique.",
  "about.trigger.label": "Le déclic",
  "about.trigger.p1": "Tout est parti d'un constat frustrant : des artisans, des indépendants, des petites entreprises avec des offres solides - mais une présence en ligne qui ne leur rendait pas justice.",
  "about.trigger.p2": "Sites bricolés sur des templates, logos faits \"par un ami\", pages qui n'expliquent même pas clairement ce qu'ils font. Nous avons créé NOVA VISIO pour leur donner les mêmes armes que les grands : une image claire, un site qui travaille pour eux, et un accompagnement sans jargon.",
  "about.vision.label": "Vision",
  "about.vision.text": "Nous ne sommes pas une agence qui vous vend un site et disparaît. Chaque projet est un vrai partenariat : nous apprenons votre métier, nous comprenons vos clients, et nous créons des outils qui",
  "about.vision.highlight": "vous rapportent concrètement",
  "about.value.clarity": "Clarté",
  "about.value.clarity.desc": "On dit les choses simplement. Pas de jargon, pas de blabla.",
  "about.value.structure": "Structure",
  "about.value.structure.desc": "Chaque décision de design a une raison. Rien n'est là par hasard.",
  "about.value.simplicity": "Simplicité",
  "about.value.simplicity.desc": "Moins de superflu, plus d'impact. L'essentiel, bien exécuté.",
  "about.value.pedagogy": "Pédagogie",
  "about.value.pedagogy.desc": "On vous explique tout. Vous restez maître de votre image.",
  "about.mission.label": "Notre mission",
  "about.mission.text": "Identité visuelle, site web, supports de communication - nous ne faisons pas tout, mais ce que nous faisons, nous le faisons bien.",
  "about.mission.highlight": "Chaque projet repart avec des outils concrets",
  "about.mission.rest": ", pas des promesses en l'air.",
  "about.method.title": "Notre",
  "about.method.highlight": "méthode.",
  "about.method.text": "Un appel, un diagnostic, une proposition claire. Si on n'est pas la bonne solution, on vous le dit.",
  "about.method.cta": "Parlons de votre projet",

  // ── Recommandation Page ──
  "recommandation.badge": "Programme de recommandation",
  "recommandation.title.1": "Recommandez.",
  "recommandation.title.highlight": "Gagnez 100 €.",
  "recommandation.subtitle.1": "Vous êtes satisfait de votre site ?",
  "recommandation.subtitle.2": "Faites-en profiter votre réseau. Pour chaque",
  "recommandation.subtitle.bold1": "nouveau client",
  "recommandation.subtitle.3": "on vous offre",
  "recommandation.subtitle.bold2": "100 €",
  "recommandation.steps.title": "3 étapes.",
  "recommandation.steps.highlight": "Zéro complication.",
  "recommandation.steps.subtitle": "Pas de formulaire compliqué.",
  "recommandation.steps.subtitle.bold": "conditions cachées",
  "recommandation.s1.title": "Vous recommandez",
  "recommandation.s1.desc": "Parlez de Nova Visio à un entrepreneur, artisan ou PME de votre réseau.",
  "recommandation.s2.title": "Il signe un projet",
  "recommandation.s2.desc": "Le nouveau client lance un projet de création de site web avec nous.",
  "recommandation.s3.title": "Vous recevez 100 €",
  "recommandation.s3.desc": "Dès la mise en ligne du site, on vous envoie votre récompense.",
  "recommandation.conditions.title": "Conditions",
  "recommandation.conditions.highlight": "simples.",
  "recommandation.conditions.subtitle.bold": "Tout est clair",
  "recommandation.conditions.subtitle": "dès le départ.",
  "recommandation.c1.label": "Montant",
  "recommandation.c1.value": "100 € par client signé.",
  "recommandation.c2.label": "Projets concernés",
  "recommandation.c2.value": "Création de site web (hors prestations ponctuelles mineures).",
  "recommandation.c3.label": "Versement",
  "recommandation.c3.value": "À la mise en ligne du site.",
  "recommandation.c4.label": "Modalités",
  "recommandation.c4.value": "Virement bancaire ou avoir sur une prochaine prestation.",
  "recommandation.c5.label": "Limite",
  "recommandation.c5.value": "Aucune. Recommandez autant de personnes que vous voulez.",
  "recommandation.cta.title": "Prêt à recommander ?",
  "recommandation.cta.subtitle.1": "Contactez-nous pour nous",
  "recommandation.cta.subtitle.bold": "transmettre le nom",
  "recommandation.cta.subtitle.2": "de la personne que vous recommandez.",
  "recommandation.cta.button": "Recommander quelqu'un →",

  // ── Blog Page ──
  "blog.page.title.1": "On partage ce qu'on",
  "blog.page.title.highlight": "sait.",
  "blog.page.subtitle": "Des articles concrets pour prendre de meilleures décisions sur votre site, votre image et votre présence en ligne.",

  // ── Tarifs Page ──
  "tarifs.badge": "Nos tarifs",
  "tarifs.title.1": "Transparence totale.",
  "tarifs.title.highlight": "Des prix clairs. Point.",
  "tarifs.subtitle": "Vous savez ce que vous payez. Pas de frais cachés, pas de surprises.",
  "tarifs.reassurance.1": "Basé en Suisse, actif en France",
  "tarifs.reassurance.2": "Livraison en 7 à 14 jours",
  "tarifs.reassurance.3": "Appel découverte gratuit inclus",
  "tarifs.complementary": "+ Services complémentaires disponibles sur demande →",
  "tarifs.packs.title.1": "Tout en un ?",
  "tarifs.packs.title.highlight": "On a ce qu'il faut.",
  "tarifs.packs.subtitle": "Site + identité visuelle dans une seule offre. Moins de prestataires, plus de cohérence, et un",
  "tarifs.packs.subtitle.bold": "meilleur prix",
  "tarifs.cta.title.1": "Vous savez ce qu'il vous faut ?",
  "tarifs.cta.title.highlight": "On en parle.",
  "tarifs.cta.subtitle": "15 min d'appel gratuit. On fait le point et on vous dit honnêtement quelle offre correspond à votre situation.",
  "tarifs.cta.button": "Demander un devis gratuit",
  "tarifs.from": "dès",
  "tarifs.startProject": "Démarrer ce projet",

  // ── Service Cards (Tarifs) ──
  "tarifs.vitrine.title": "Site vitrine",
  "tarifs.vitrine.subtitle": "Votre meilleur commercial",
  "tarifs.vitrine.badge": "Best-seller",
  "tarifs.landing.title": "Landing page",
  "tarifs.landing.subtitle": "Un message, une action",
  "tarifs.landing.badge": "Starter",
  "tarifs.identity.title": "Identité visuelle",
  "tarifs.identity.subtitle": "Fini le logo bricolé",
  "tarifs.identity.badge": "Sur-mesure",

  // ── Web Service Page ──
  "web.hero.badge": "Création de sites web & landing pages",
  "web.hero.title.1": "Votre site.",
  "web.hero.title.highlight": "Votre meilleur commercial.",
  "web.hero.subtitle": "Ce que vous faites, pourquoi vous faire confiance, comment travailler avec vous. Un site qui convertit. Point.",
  "web.hero.bullet1": "Des pages structurées qui expliquent clairement votre offre.",
  "web.hero.bullet2": "Un design qui rassure vos prospects - pas qui vous flatte.",
  "web.hero.bullet3": "Un site que vous pouvez modifier vous-même, sans appeler un développeur.",
  "web.hero.price": "Site vitrine dès 1'500 CHF - Livraison en 7 à 14 jours",
  "web.hero.cta.primary": "Réserver un appel gratuit →",
  "web.hero.cta.secondary": "Voir les tarifs →",
  "web.content.title": "Un beau site qui ne vend pas, c'est juste une jolie vitrine vide.",
  "web.content.p1.1": "Vos prospects arrivent sur votre site. En 3 secondes, ils décident de rester ou de partir. Ce qui fait la différence ? Pas les animations ou les effets - mais une structure qui dit clairement",
  "web.content.p1.bold": " qui vous êtes, ce que vous proposez, et pourquoi vous faire confiance",
  "web.content.p2": "Nous partons de votre activité, de vos vrais objectifs, et nous construisons un site où chaque page a un rôle précis : rassurer, guider, convaincre. Le design est au service du parcours, pas l'inverse. Résultat : vos visiteurs comprennent votre offre et passent à l'action - prise de contact, demande de devis, achat.",
  "web.content.cta": "Parler de votre projet",
  "web.maintenance.text": "Votre site est livré - mais votre présence en ligne ne s'arrête pas là. Mises à jour, modifs de contenu, suivi des performances : notre suivi mensuel à 89 CHF/mois prend le relais pour que votre site reste un outil qui bosse pour vous.",

  // ── Brand Service Page ──
  "brand.maintenance.text": "Votre identité est livrée - maintenant il faut la déployer partout sans se perdre. Notre suivi mensuel à 89 CHF/mois veille sur votre présence en ligne pendant que vous vous concentrez sur votre métier.",

  // ── Final CTA Sections ──
  "finalcta.web.title.1": "Prêt ?",
  "finalcta.web.title.highlight": "On y va.",
  "finalcta.web.subtitle.bold1": "15 minutes",
  "finalcta.web.subtitle.1": "d'appel gratuit.",
  "finalcta.web.subtitle.bold2": "solution claire",
  "finalcta.web.subtitle.2": "On regarde ce qui bloque et on propose une",
  "finalcta.web.cta": "Réserver un appel gratuit",
  "finalcta.brand.title.1": "Votre image mérite",
  "finalcta.brand.title.highlight": "mieux.",
  "finalcta.brand.subtitle.bold1": "15 minutes",
  "finalcta.brand.subtitle.1": "d'appel gratuit.",
  "finalcta.brand.subtitle.bold2": "refonte vaut le coup",
  "finalcta.brand.subtitle.2": "On vous dit franchement si une",
  "finalcta.brand.cta": "Réserver un appel gratuit",

  // ── Chatbot ──
  "chat.bubble.label": "Une question ?",
  "chat.bubble.ariaClose": "Fermer le chat",
  "chat.bubble.ariaOpen": "Parler avec Visio",
  "chat.header.title": "Parler avec Visio",
  "chat.header.subtitle": "Questions sur Nova Visio ou les offres ?",
  "chat.welcome": "Bonjour ! Je suis",
  "chat.welcome.name": "Visio",
  "chat.welcome.rest": ", l'assistant du studio.",
  "chat.welcome.question": "Comment puis-je vous aider ?",
  "chat.suggestion.1": "Quels services proposez-vous ?",
  "chat.suggestion.2": "Combien coûte un site web ?",
  "chat.suggestion.3": "Quelle est la durée d'un projet ?",
  "chat.input.placeholder": "Posez votre question...",
  "chat.error.prefix": "Désolé,",
  "chat.error.suffix": ". Veuillez réessayer ou contacter le studio directement via la page Contact.",

  // ── Cookie Consent ──
  "cookie.text": "Ce site utilise des cookies pour améliorer votre expérience.",
  "cookie.accept": "Accepter",

  // ── Not Found ──
  "notfound.title": "Page non trouvée",
  "notfound.subtitle": "La page que vous cherchez n'existe pas.",
  "notfound.cta": "Retour à l'accueil",

  // ── Validation ──
  "validation.firstName": "Prénom requis",
  "validation.lastName": "Nom requis",
  "validation.email": "Email invalide",
  "validation.message.min": "Minimum 10 caractères",
  "validation.message.max": "2000 caractères max",
  "validation.max50": "50 caractères max",
  "validation.max100": "100 caractères max",
};

// ─── ENGLISH TRANSLATIONS ──────────────────────────────────────
const en: Record<string, string> = {
  // ── Navbar ──
  "nav.home": "Home",
  "nav.services": "Services",
  "nav.services.web": "Website",
  "nav.services.brand": "Logo & Brand Identity",
  "nav.pricing": "Pricing",
  "nav.referral": "Referral",
  "nav.blog": "Blog",
  "nav.about": "About",
  "nav.contact": "Contact",
  "nav.cta": "Let's talk about your project",

  // ── Hero ──
  "hero.badge": "Made in Switzerland · Craftspeople, freelancers & SMEs",
  "hero.title.line1": "Your talent deserves",
  "hero.title.highlight": "to be seen.",
  "hero.subtitle": "Showcase website, landing page, brand identity.",
  "hero.subtitle2": "The tools to be seen, understood",
  "hero.subtitle3": "and contacted. From",
  "hero.subtitle.price": "900 CHF",
  "hero.cta.primary": "Book a free call",
  "hero.cta.secondary": "Explore our services",

  // ── Services Section (Home) ──
  "services.title.line1": "Two expertises.",
  "services.title.highlight": "One single goal.",
  "services.subtitle.1": "Be seen",
  "services.subtitle.2": "Be understood",
  "services.subtitle.3": "Be chosen",
  "services.web.title": "Showcase website and landing page",
  "services.web.description": "Your prospects land, understand your offer in 5 seconds and reach out. That's what a great website does.",
  "services.web.cta": "Explore our web projects →",
  "services.web.price": "from 900 CHF",
  "services.brand.title": "Brand identity & logo",
  "services.brand.description": "No more DIY logos. A real identity that sets you apart and works across every touchpoint.",
  "services.brand.cta": "See our brand identities →",
  "services.brand.price": "from 900 CHF",
  "services.badge": "FOR: CRAFTSPEOPLE, SMES, FREELANCERS, STARTUPS",

  // ── Web Benefits ──
  "services.web.b1": "Build credibility",
  "services.web.b1h": "from the very first second",
  "services.web.b2": "Turn visitors",
  "services.web.b2h": "into qualified leads",
  "services.web.b3": "Present your services",
  "services.web.b3h": "with clarity and impact",
  "services.web.b4": "Rank on Google",
  "services.web.b4h": "with built-in SEO",
  "services.web.b5": "A fast, smooth website",
  "services.web.b5h": "on mobile and desktop",

  // ── Brand Benefits ──
  "services.brand.b1": "Be recognised",
  "services.brand.b1h": "at first glance",
  "services.brand.b2": "Inspire trust",
  "services.brand.b2h": "before you even speak",
  "services.brand.b3": "A consistent image",
  "services.brand.b3h": "across all your touchpoints",
  "services.brand.b4": "Stand out",
  "services.brand.b4h": "from your competitors",
  "services.brand.b5": "A professional logo",
  "services.brand.b5h": "ready for any format",
  "services.brand.b6": "Brand guidelines",
  "services.brand.b6h": "that are easy to follow",

  // ── Maintenance Section (Home) ──
  "maintenance.badge": "🔄 Ongoing support",
  "maintenance.title.1": "Delivered.",
  "maintenance.title.2": "Then supported.",
  "maintenance.subtitle": "performance, updates.",
  "maintenance.subtitle.bold1": "Updates",
  "maintenance.subtitle.bold2": "working for you",

  // ── Maintenance Card ──
  "maintenance.card.bestseller": "⭐ Best-seller",
  "maintenance.card.title": "Support & Maintenance",
  "maintenance.card.subtitle": "Your site stays performant — with zero effort on your end.",
  "maintenance.card.from": "from",
  "maintenance.card.price": "89 CHF/month",
  "maintenance.card.nocommit": "No commitment — cancel anytime",
  "maintenance.card.f1": "Hosting & domain name",
  "maintenance.card.f1h": "managed",
  "maintenance.card.f2": "Technical updates",
  "maintenance.card.f2h": "& security",
  "maintenance.card.f3": "Automatic backups",
  "maintenance.card.f3h": "weekly",
  "maintenance.card.f4": "1 hour of content",
  "maintenance.card.f4h": "updates per month",
  "maintenance.card.f5": "Monthly performance report",
  "maintenance.card.f5h": "(visits, leads)",
  "maintenance.card.f6": "Responsive support",
  "maintenance.card.f6h": "within 48 hours",
  "maintenance.card.cta": "Activate support",
  "maintenance.card.included": "Automatically included at the end of every project.",

  // ── Benefits Section (Home) ──
  "benefits.title.1": "What it changes.",
  "benefits.title.2": "Concretely.",
  "benefits.subtitle": "When your image and your website",
  "benefits.subtitle2": "finally do the heavy lifting.",
  "benefits.b1.text": "Your clients understand ",
  "benefits.b1.highlight": "in seconds",
  "benefits.b1.rest": " what you do — no more repeating yourself.",
  "benefits.b2.text": "You have a ",
  "benefits.b2.highlight": "professional, consistent image",
  "benefits.b2.rest": " across all your channels, without spending your evenings on it.",
  "benefits.b3.text": "You ",
  "benefits.b3.highlight": "attract the right clients",
  "benefits.b3.rest": " — those who appreciate your value and don't haggle on price.",
  "benefits.b4.text": "Your ",
  "benefits.b4.highlight": "digital mental load drops",
  "benefits.b4.rest": ": everything's in place, so you can focus on your craft.",

  // ── Why Us Section ──
  "whyus.badge": "What sets us apart",
  "whyus.title.1": "NOVA VISIO.",
  "whyus.title.highlight": "The difference.",
  "whyus.r1.title": "Zero jargon",
  "whyus.r1.desc": "We speak like humans. No \"UX synergies\" or \"digital paradigms\".",
  "whyus.r2.title": "Genuine\nsupport",
  "whyus.r2.desc": "We don't disappear after delivery. We're here as long as you need us.",
  "whyus.r3.title": "Quality > quantity",
  "whyus.r3.desc": "We take on few projects at a time. Each one gets our full attention.",
  "whyus.r4.title": "Results,\nnot promises",
  "whyus.r4.desc": "We don't sell dreams. We build tools that actually work for you.",

  // ── Steps Section (Home) ──
  "steps.title": "5 steps.",
  "steps.title.highlight": "Zero guesswork.",
  "steps.subtitle.bold1": "simple",
  "steps.subtitle.bold2": "transparent",
  "steps.subtitle.rest": "from start to finish.",
  "steps.s1.title": "We talk",
  "steps.s1.subtitle": "15 min",
  "steps.s1.desc": "A free call to understand your business, your goals, and what's holding you back.",
  "steps.s2.title": "We assess",
  "steps.s2.subtitle": "your situation",
  "steps.s2.desc": "We review what's in place — site, image, messaging — and pinpoint what needs to change.",
  "steps.s3.title": "We build",
  "steps.s3.subtitle": "the foundations",
  "steps.s3.desc": "Positioning, visual identity, message structure. Solid groundwork before design.",
  "steps.s4.title": "We create",
  "steps.s4.subtitle": "your site",
  "steps.s4.desc": "Custom design, conversion-driven pages, seamless experience on every screen.",
  "steps.s5.title": "We launch",
  "steps.s5.subtitle": "& follow up",
  "steps.s5.desc": "Go live, quick training, and monthly support to keep your site effective.",
  "steps.bottom": "A transparent, collaborative process",

  // ── CTA Section (Home) ──
  "cta.title.1": "15 minutes.",
  "cta.title.highlight": "No strings attached.",
  "cta.subtitle.1": "We'll review",
  "cta.subtitle.bold1": "your situation",
  "cta.subtitle.2": "and tell you",
  "cta.subtitle.bold2": "honestly",
  "cta.subtitle.3": "if we can help.",
  "cta.primary": "Book a free call →",
  "cta.secondary": "See our pricing →",

  // ── Referral CTA ──
  "referral.title.1": "Refer Nova Visio.",
  "referral.title.highlight": "Earn €100.",
  "referral.subtitle.1": "Know someone launching a business?",
  "referral.subtitle.bold1": "Tell them about us",
  "referral.subtitle.2": "If they sign a website project, you receive",
  "referral.subtitle.bold2": "€100",
  "referral.cta": "Discover the programme →",

  // ── Blog Section (Home) ──
  "blog.title.1": "We share. We",
  "blog.title.highlight": "enlighten.",
  "blog.subtitle.bold1": "practical",
  "blog.subtitle.1": "articles about your site,",
  "blog.subtitle.bold2": "online presence",
  "blog.subtitle.2": "your image and your",
  "blog.readArticle": "Read article",
  "blog.viewAll": "View all articles",

  // ── Footer ──
  "footer.rights": "All rights reserved.",

  // ── Contact Page ──
  "contact.title.1": "Let's talk.",
  "contact.title.highlight": "15 minutes.",
  "contact.subtitle.bold1": "your situation",
  "contact.subtitle.1": "We'll review",
  "contact.subtitle.2": "No sales pitch.",
  "contact.subtitle.bold2": "honest conversation",
  "contact.subtitle.3": "Just an",
  "contact.form.firstName": "First name",
  "contact.form.firstName.placeholder": "Your first name",
  "contact.form.lastName": "Last name",
  "contact.form.lastName.placeholder": "Your last name",
  "contact.form.email": "Email",
  "contact.form.email.placeholder": "your@email.com",
  "contact.form.projectType": "Project type",
  "contact.form.projectType.placeholder": "Select a project type",
  "contact.form.projectType.call": "Free discovery call (15 min)",
  "contact.form.projectType.website": "Showcase website",
  "contact.form.projectType.landing": "Landing page",
  "contact.form.projectType.brand": "Brand identity & logo",
  "contact.form.projectType.packDigital": "Digital & Branding Pack",
  "contact.form.projectType.packRefonte": "Complete Rebrand Pack",
  "contact.form.projectType.maintenance": "Support & Maintenance",
  "contact.form.projectType.other": "Other / Question",
  "contact.form.message": "Message",
  "contact.form.message.placeholder": "Describe your project and goals...",
  "contact.form.submit": "Send my enquiry",
  "contact.form.submitting": "Sending...",
  "contact.form.reassurance": "✓ Reply within 24h   ✓ No commitment   ✓ Call in English or French",
  "contact.form.success.title": "Message sent!",
  "contact.form.success.desc": "We'll get back to you within 24 to 48 hours.",
  "contact.form.error.title": "Error",
  "contact.form.error.desc": "Something went wrong. Please try again.",
  "contact.form.validation.title": "Validation error",
  "contact.form.validation.desc": "Please fix the errors in the form.",
  "contact.whatNext.fast.title": "Fast response",
  "contact.whatNext.fast.desc": "We'll get back to you within 24 to 48 hours.",
  "contact.whatNext.noPressure.title": "No pressure",
  "contact.whatNext.noPressure.item1": "Constructive discussion",
  "contact.whatNext.noPressure.item2": "Tailored solutions",
  "contact.booking.title": "Or book a",
  "contact.booking.highlight": "time slot",

  // ── About Page ──
  "about.title": "Who we",
  "about.title.highlight": "are.",
  "about.subtitle": "Too many entrepreneurs deserve better",
  "about.subtitle2": "than a website built on a generic template.",
  "about.trigger.label": "The spark",
  "about.trigger.p1": "It all started from a frustrating observation: craftspeople, freelancers, and small businesses with solid offerings — but an online presence that didn't do them justice.",
  "about.trigger.p2": "Cobbled-together template websites, logos made \"by a friend\", pages that didn't even clearly explain what they do. We created NOVA VISIO to give them the same tools as the big players: a clear image, a website that works for them, and support without jargon.",
  "about.vision.label": "Vision",
  "about.vision.text": "We're not an agency that sells you a site and vanishes. Every project is a genuine partnership: we learn your business, understand your clients, and create tools that",
  "about.vision.highlight": "deliver real results",
  "about.value.clarity": "Clarity",
  "about.value.clarity.desc": "We say things simply. No jargon, no fluff.",
  "about.value.structure": "Structure",
  "about.value.structure.desc": "Every design decision has a reason. Nothing is there by accident.",
  "about.value.simplicity": "Simplicity",
  "about.value.simplicity.desc": "Less noise, more impact. The essentials, done well.",
  "about.value.pedagogy": "Guidance",
  "about.value.pedagogy.desc": "We explain everything. You stay in control of your image.",
  "about.mission.label": "Our mission",
  "about.mission.text": "Visual identity, website, marketing materials — we don't do everything, but what we do, we do it well.",
  "about.mission.highlight": "Every project leaves with concrete tools",
  "about.mission.rest": ", not empty promises.",
  "about.method.title": "Our",
  "about.method.highlight": "approach.",
  "about.method.text": "A call, an assessment, a clear proposal. If we're not the right fit, we'll tell you.",
  "about.method.cta": "Let's talk about your project",

  // ── Recommandation Page ──
  "recommandation.badge": "Referral programme",
  "recommandation.title.1": "Refer us.",
  "recommandation.title.highlight": "Earn €100.",
  "recommandation.subtitle.1": "Happy with your website?",
  "recommandation.subtitle.2": "Spread the word. For every",
  "recommandation.subtitle.bold1": "new client",
  "recommandation.subtitle.3": "we give you",
  "recommandation.subtitle.bold2": "€100",
  "recommandation.steps.title": "3 steps.",
  "recommandation.steps.highlight": "Zero hassle.",
  "recommandation.steps.subtitle": "No complicated forms.",
  "recommandation.steps.subtitle.bold": "hidden conditions",
  "recommandation.s1.title": "You refer",
  "recommandation.s1.desc": "Tell an entrepreneur, craftsperson or SME in your network about Nova Visio.",
  "recommandation.s2.title": "They sign a project",
  "recommandation.s2.desc": "The new client starts a website project with us.",
  "recommandation.s3.title": "You receive €100",
  "recommandation.s3.desc": "Once the site goes live, we send you your reward.",
  "recommandation.conditions.title": "Straightforward",
  "recommandation.conditions.highlight": "terms.",
  "recommandation.conditions.subtitle.bold": "Everything is clear",
  "recommandation.conditions.subtitle": "from the start.",
  "recommandation.c1.label": "Amount",
  "recommandation.c1.value": "€100 per signed client.",
  "recommandation.c2.label": "Eligible projects",
  "recommandation.c2.value": "Website creation (excluding minor one-off services).",
  "recommandation.c3.label": "Payment",
  "recommandation.c3.value": "Upon site launch.",
  "recommandation.c4.label": "Method",
  "recommandation.c4.value": "Bank transfer or credit towards a future project.",
  "recommandation.c5.label": "Limit",
  "recommandation.c5.value": "None. Refer as many people as you'd like.",
  "recommandation.cta.title": "Ready to refer?",
  "recommandation.cta.subtitle.1": "Get in touch to",
  "recommandation.cta.subtitle.bold": "share the name",
  "recommandation.cta.subtitle.2": "of the person you're referring.",
  "recommandation.cta.button": "Refer someone →",

  // ── Blog Page ──
  "blog.page.title.1": "We share what we",
  "blog.page.title.highlight": "know.",
  "blog.page.subtitle": "Practical articles to help you make better decisions about your website, your image, and your online presence.",

  // ── Tarifs Page ──
  "tarifs.badge": "Our pricing",
  "tarifs.title.1": "Total transparency.",
  "tarifs.title.highlight": "Clear pricing. Period.",
  "tarifs.subtitle": "You know what you're paying for. No hidden fees, no surprises.",
  "tarifs.reassurance.1": "Based in Switzerland, active in France",
  "tarifs.reassurance.2": "Delivery in 7 to 14 days",
  "tarifs.reassurance.3": "Free discovery call included",
  "tarifs.complementary": "+ Additional services available on request →",
  "tarifs.packs.title.1": "Want it all?",
  "tarifs.packs.title.highlight": "We've got you covered.",
  "tarifs.packs.subtitle": "Website + brand identity in a single offer. Fewer providers, more consistency, and a",
  "tarifs.packs.subtitle.bold": "better price",
  "tarifs.cta.title.1": "Know what you need?",
  "tarifs.cta.title.highlight": "Let's talk.",
  "tarifs.cta.subtitle": "15-minute free call. We'll assess your needs and honestly recommend the right package for you.",
  "tarifs.cta.button": "Request a free quote",
  "tarifs.from": "from",
  "tarifs.startProject": "Start this project",

  // ── Service Cards (Tarifs) ──
  "tarifs.vitrine.title": "Showcase website",
  "tarifs.vitrine.subtitle": "Your best salesperson",
  "tarifs.vitrine.badge": "Best-seller",
  "tarifs.landing.title": "Landing page",
  "tarifs.landing.subtitle": "One message, one action",
  "tarifs.landing.badge": "Starter",
  "tarifs.identity.title": "Brand identity",
  "tarifs.identity.subtitle": "No more DIY logos",
  "tarifs.identity.badge": "Bespoke",

  // ── Web Service Page ──
  "web.hero.badge": "Website & landing page creation",
  "web.hero.title.1": "Your website.",
  "web.hero.title.highlight": "Your best salesperson.",
  "web.hero.subtitle": "What you do, why they should trust you, how to work with you. A site that converts. Simple.",
  "web.hero.bullet1": "Structured pages that clearly explain your offering.",
  "web.hero.bullet2": "A design that reassures your prospects — not just flatters you.",
  "web.hero.bullet3": "A site you can update yourself, without calling a developer.",
  "web.hero.price": "Showcase website from 1,500 CHF — Delivery in 7 to 14 days",
  "web.hero.cta.primary": "Book a free call →",
  "web.hero.cta.secondary": "See pricing →",
  "web.content.title": "A beautiful site that doesn't sell is just a pretty empty shopfront.",
  "web.content.p1.1": "Your prospects land on your site. In 3 seconds, they decide to stay or leave. What makes the difference? Not animations or effects — but a structure that clearly says",
  "web.content.p1.bold": " who you are, what you offer, and why they should trust you",
  "web.content.p2": "We start from your business, your real objectives, and we build a site where every page has a clear purpose: reassure, guide, convince. Design serves the journey, not the other way around. Result: your visitors understand your offer and take action — enquiry, quote request, purchase.",
  "web.content.cta": "Talk about your project",
  "web.maintenance.text": "Your site is delivered — but your online presence doesn't stop there. Updates, content changes, performance tracking: our monthly support at 89 CHF/month takes over so your site keeps working for you.",

  // ── Brand Service Page ──
  "brand.maintenance.text": "Your identity is delivered — now it needs to be deployed everywhere without losing consistency. Our monthly support at 89 CHF/month takes care of your online presence while you focus on your craft.",

  // ── Final CTA Sections ──
  "finalcta.web.title.1": "Ready?",
  "finalcta.web.title.highlight": "Let's go.",
  "finalcta.web.subtitle.bold1": "15 minutes",
  "finalcta.web.subtitle.1": "free call.",
  "finalcta.web.subtitle.bold2": "clear solution",
  "finalcta.web.subtitle.2": "We'll review what's holding you back and propose a",
  "finalcta.web.cta": "Book a free call",
  "finalcta.brand.title.1": "Your image deserves",
  "finalcta.brand.title.highlight": "better.",
  "finalcta.brand.subtitle.bold1": "15 minutes",
  "finalcta.brand.subtitle.1": "free call.",
  "finalcta.brand.subtitle.bold2": "rebrand is worth it",
  "finalcta.brand.subtitle.2": "We'll honestly tell you whether a",
  "finalcta.brand.cta": "Book a free call",

  // ── Chatbot ──
  "chat.bubble.label": "Any questions?",
  "chat.bubble.ariaClose": "Close chat",
  "chat.bubble.ariaOpen": "Chat with Visio",
  "chat.header.title": "Chat with Visio",
  "chat.header.subtitle": "Questions about Nova Visio or our services?",
  "chat.welcome": "Hello! I'm",
  "chat.welcome.name": "Visio",
  "chat.welcome.rest": ", the studio's assistant.",
  "chat.welcome.question": "How can I help you?",
  "chat.suggestion.1": "What services do you offer?",
  "chat.suggestion.2": "How much does a website cost?",
  "chat.suggestion.3": "How long does a project take?",
  "chat.input.placeholder": "Ask your question...",
  "chat.error.prefix": "Sorry,",
  "chat.error.suffix": ". Please try again or contact the studio directly via the Contact page.",

  // ── Cookie Consent ──
  "cookie.text": "This site uses cookies to improve your experience.",
  "cookie.accept": "Accept",

  // ── Not Found ──
  "notfound.title": "Page not found",
  "notfound.subtitle": "The page you're looking for doesn't exist.",
  "notfound.cta": "Back to home",

  // ── Validation ──
  "validation.firstName": "First name required",
  "validation.lastName": "Last name required",
  "validation.email": "Invalid email",
  "validation.message.min": "Minimum 10 characters",
  "validation.message.max": "2,000 characters max",
  "validation.max50": "50 characters max",
  "validation.max100": "100 characters max",
};
