import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "fr" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("nova-visio-lang");
    if (saved === "en" || saved === "fr") return saved;
    const browserLang = navigator.language.toLowerCase();
    return browserLang.startsWith("en") ? "en" : "fr";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("nova-visio-lang", lang);
    document.documentElement.lang = lang;
  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    const translations = language === "fr" ? fr : en;
    return (translations as Record<string, string>)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
}

// ─── FRENCH TRANSLATIONS ───────────────────────────────────────
const fr: Record<string, string> = {
  // ── Navbar ──
  "nav.home": "Accueil",
  "nav.services": "Services",
  "nav.services.web": "Site web",
  "nav.services.brand": "Logo & identité visuelle",
  "nav.pricing": "Tarifs",
  "nav.referral": "Recommandation",
  "nav.blog": "Blog",
  "nav.about": "À propos",
  "nav.contact": "Contact",
  "nav.cta": "Parlons de votre projet",

  // ── Hero ──
  "hero.badge": "Made in Switzerland · Artisans, indépendants & PME",
  "hero.title.line1": "Votre talent mérite",
  "hero.title.highlight": "d'être vu.",
  "hero.subtitle": "Site vitrine, landing page, identité visuelle.",
  "hero.subtitle2": "Les outils pour être vu, compris",
  "hero.subtitle3": "et contacté. Dès",
  "hero.subtitle.price": "900 CHF",
  "hero.cta.primary": "Réserver un appel gratuit",
  "hero.cta.secondary": "Découvrir nos services",

  // ── Services Section (Home) ──
  "services.title.line1": "Deux expertises.",
  "services.title.highlight": "Un seul objectif.",
  "services.subtitle.1": "Être vu",
  "services.subtitle.2": "Être compris",
  "services.subtitle.3": "Être choisi",
  "services.web.title": "Site vitrine et landing page",
  "services.web.description": "Vos prospects arrivent, comprennent votre offre en 5 secondes et vous contactent. C'est ça, un bon site.",
  "services.web.cta": "Découvrir nos créations web →",
  "services.web.price": "dès 900 CHF",
  "services.brand.title": "Identité visuelle & logo",
  "services.brand.description": "Fini le logo fait sur Canva. Une vraie identité qui vous démarque et que vous pouvez utiliser partout.",
  "services.brand.cta": "Voir nos identités visuelles →",
  "services.brand.price": "dès 900 CHF",
  "services.badge": "POUR : ARTISANS, PME, FREELANCES, STARTUP",
  "services.web.b1": "Gagnez en crédibilité",
  "services.web.b1h": "dès les premières secondes",
  "services.web.b2": "Convertissez vos visiteurs",
  "services.web.b2h": "en clients qualifiés",
  "services.web.b3": "Présentez vos offres",
  "services.web.b3h": "avec clarté et impact",
  "services.web.b4": "Soyez visible sur Google",
  "services.web.b4h": "grâce au référencement naturel",
  "services.web.b5": "Un site rapide et fluide",
  "services.web.b5h": "sur mobile comme sur ordinateur",
  "services.brand.b1": "Soyez reconnu",
  "services.brand.b1h": "au premier coup d'œil",
  "services.brand.b2": "Inspirez confiance",
  "services.brand.b2h": "avant même de parler",
  "services.brand.b3": "Une image cohérente",
  "services.brand.b3h": "sur tous vos supports",
  "services.brand.b4": "Démarquez-vous",
  "services.brand.b4h": "de vos concurrents",
  "services.brand.b5": "Un logo professionnel",
  "services.brand.b5h": "déclinable partout",
  "services.brand.b6": "Une charte graphique",
  "services.brand.b6h": "simple à appliquer",

  // ── Maintenance Section (Home) ──
  "maintenance.badge": "🔄 Suivi continu",
  "maintenance.title.1": "Livré.",
  "maintenance.title.2": "Puis suivi.",
  "maintenance.subtitle": "performances, modifications.",
  "maintenance.subtitle.bold1": "Mises à jour",
  "maintenance.subtitle.bold2": "travailler pour vous",
  "maintenance.card.bestseller": "⭐ Best-seller",
  "maintenance.card.title": "Suivi & Maintenance",
  "maintenance.card.subtitle": "Votre site reste performant, sans effort de votre part.",
  "maintenance.card.from": "dès",
  "maintenance.card.price": "89 CHF/mois",
  "maintenance.card.nocommit": "Sans engagement - résiliable à tout moment",
  "maintenance.card.f1": "Hébergement & nom de domaine",
  "maintenance.card.f1h": "géré",
  "maintenance.card.f2": "Mises à jour techniques",
  "maintenance.card.f2h": "& sécurité",
  "maintenance.card.f3": "Sauvegardes automatiques",
  "maintenance.card.f3h": "hebdomadaires",
  "maintenance.card.f4": "1h de modifications",
  "maintenance.card.f4h": "de contenu par mois",
  "maintenance.card.f5": "Rapport mensuel de performance",
  "maintenance.card.f5h": "(visites, contacts)",
  "maintenance.card.f6": "Support réactif",
  "maintenance.card.f6h": "sous 48h",
  "maintenance.card.cta": "Activer le suivi",
  "maintenance.card.included": "Inclus automatiquement à la fin de chaque projet.",

  // ── Benefits Section (Home) ──
  "benefits.title.1": "Ce que ça change.",
  "benefits.title.2": "Concrètement.",
  "benefits.subtitle": "Quand votre image et votre site",
  "benefits.subtitle2": "font enfin le job.",
  "benefits.b1.text": "Vos clients comprennent ",
  "benefits.b1.highlight": "en quelques secondes",
  "benefits.b1.rest": " ce que vous faites - plus besoin d'expliquer 10 fois.",
  "benefits.b2.text": "Vous avez une ",
  "benefits.b2.highlight": "image pro et cohérente",
  "benefits.b2.rest": " sur tous vos supports, sans y passer vos soirées.",
  "benefits.b3.text": "Vous ",
  "benefits.b3.highlight": "attirez les bons clients",
  "benefits.b3.rest": " - ceux qui comprennent votre valeur et ne négocient pas vos prix.",
  "benefits.b4.text": "Votre ",
  "benefits.b4.highlight": "charge mentale digitale diminue",
  "benefits.b4.rest": " : tout est en place, vous pouvez bosser sur votre métier.",

  // ── Why Us Section ──
  "whyus.badge": "Notre différence",
  "whyus.title.1": "NOVA VISIO.",
  "whyus.title.highlight": "La différence.",
  "whyus.r1.title": "Zéro jargon",
  "whyus.r1.desc": "On parle comme des humains. Pas de \"synergie UX\" ni de \"paradigme digital\".",
  "whyus.r2.title": "Un vrai\naccompagnement",
  "whyus.r2.desc": "On ne vous lâche pas après la livraison. On reste là tant que vous avez besoin.",
  "whyus.r3.title": "Qualité > quantité",
  "whyus.r3.desc": "On prend peu de projets à la fois. Chacun a notre attention complète.",
  "whyus.r4.title": "Résultats,\npas promesses",
  "whyus.r4.desc": "On ne vend pas du rêve. On construit des outils qui travaillent pour vous.",

  // ── Steps Section (Home) ──
  "steps.title": "5 étapes.",
  "steps.title.highlight": "Zéro flou.",
  "steps.subtitle.bold1": "simple",
  "steps.subtitle.bold2": "transparent",
  "steps.subtitle.rest": "du début à la fin.",
  "steps.s1.title": "On échange",
  "steps.s1.subtitle": "15 min",
  "steps.s1.desc": "Un appel gratuit pour comprendre votre activité, vos objectifs et ce qui bloque aujourd'hui.",
  "steps.s2.title": "On diagnostique",
  "steps.s2.subtitle": "votre situation",
  "steps.s2.desc": "On analyse ce qui existe - site, image, messages - et on identifie ce qui doit changer.",
  "steps.s3.title": "On construit",
  "steps.s3.subtitle": "les fondations",
  "steps.s3.desc": "Positionnement, identité visuelle, structure des messages. Les bases solides avant le design.",
  "steps.s4.title": "On crée",
  "steps.s4.subtitle": "votre site",
  "steps.s4.desc": "Design sur mesure, pages structurées pour convaincre, expérience fluide sur tous les écrans.",
  "steps.s5.title": "On lance",
  "steps.s5.subtitle": "& on suit",
  "steps.s5.desc": "Mise en ligne, formation rapide, et suivi mensuel pour que votre site reste un outil efficace.",
  "steps.bottom": "Processus transparent et collaboratif",

  // ── CTA Section (Home) ──
  "cta.title.1": "15 minutes.",
  "cta.title.highlight": "Sans engagement.",
  "cta.subtitle.1": "On fait le point sur",
  "cta.subtitle.bold1": "votre situation",
  "cta.subtitle.2": "On vous dit",
  "cta.subtitle.bold2": "franchement",
  "cta.subtitle.3": "si on peut vous aider.",
  "cta.primary": "Réserver un appel gratuit →",
  "cta.secondary": "Voir nos tarifs →",

  // ── Referral CTA ──
  "referral.title.1": "Recommandez Nova Visio.",
  "referral.title.highlight": "Gagnez 100 CHF.",
  "referral.subtitle.1": "Un proche lance son activité ?",
  "referral.subtitle.bold1": "Parlez-lui de nous",
  "referral.subtitle.2": "S'il signe un site web, vous recevez",
  "referral.subtitle.bold2": "100 CHF",
  "referral.cta": "Découvrir le programme →",

  // ── Blog Section (Home) ──
  "blog.title.1": "On partage. On",
  "blog.title.highlight": "éclaire.",
  "blog.subtitle.bold1": "concrets",
  "blog.subtitle.1": "sur votre site,",
  "blog.subtitle.bold2": "présence en ligne",
  "blog.subtitle.2": "votre image et votre",
  "blog.readArticle": "Lire l'article",
  "blog.viewAll": "Voir tous les articles",

  // ── Footer ──
  "footer.rights": "Tous droits réservés.",

  // ── Contact Page ──
  "contact.title.1": "Parlons-en.",
  "contact.title.highlight": "15 minutes.",
  "contact.subtitle.bold1": "votre situation",
  "contact.subtitle.1": "On fait le point sur",
  "contact.subtitle.2": "Pas de pitch commercial.",
  "contact.subtitle.bold2": "conversation honnête",
  "contact.subtitle.3": "Juste une",
  "contact.form.firstName": "Prénom",
  "contact.form.firstName.placeholder": "Votre prénom",
  "contact.form.lastName": "Nom",
  "contact.form.lastName.placeholder": "Votre nom",
  "contact.form.email": "Email",
  "contact.form.email.placeholder": "votre@email.com",
  "contact.form.projectType": "Type de projet",
  "contact.form.projectType.placeholder": "Sélectionnez un type de projet",
  "contact.form.projectType.call": "Appel découverte gratuit (15 min)",
  "contact.form.projectType.website": "Site vitrine",
  "contact.form.projectType.landing": "Landing page",
  "contact.form.projectType.brand": "Identité visuelle & logo",
  "contact.form.projectType.packDigital": "Pack Digital & Branding",
  "contact.form.projectType.packRefonte": "Pack Refonte Globale",
  "contact.form.projectType.maintenance": "Suivi & Maintenance",
  "contact.form.projectType.other": "Autre / Question",
  "contact.form.message": "Message",
  "contact.form.message.placeholder": "Décrivez votre projet et vos objectifs...",
  "contact.form.submit": "Envoyer ma demande",
  "contact.form.submitting": "Envoi en cours...",
  "contact.form.reassurance": "✓ Réponse sous 24h   ✓ Sans engagement   ✓ Appel en français",
  "contact.form.success.title": "Message envoyé !",
  "contact.form.success.desc": "Nous vous répondrons sous 24 à 48 heures.",
  "contact.form.error.title": "Erreur",
  "contact.form.error.desc": "Une erreur est survenue. Veuillez réessayer.",
  "contact.form.validation.title": "Erreur de validation",
  "contact.form.validation.desc": "Veuillez corriger les erreurs du formulaire.",
  "contact.whatNext.fast.title": "Réponse rapide",
  "contact.whatNext.fast.desc": "Nous vous répondrons sous 24 à 48 heures.",
  "contact.whatNext.noPressure.title": "Sans pression",
  "contact.whatNext.noPressure.item1": "Discussion constructive",
  "contact.whatNext.noPressure.item2": "Solutions adaptées",
  "contact.booking.title": "Ou réservez directement un",
  "contact.booking.highlight": "créneau",

  // ── About Page ──
  "about.title": "Qui sommes-",
  "about.title.highlight": "nous.",
  "about.subtitle": "Trop d'entrepreneurs méritent mieux",
  "about.subtitle2": "qu'un site sur un template générique.",
  "about.trigger.label": "Le déclic",
  "about.trigger.p1": "Tout est parti d'un constat frustrant : des artisans, des indépendants, des petites entreprises avec des offres solides - mais une présence en ligne qui ne leur rendait pas justice.",
  "about.trigger.p2": "Sites bricolés sur des templates, logos faits \"par un ami\", pages qui n'expliquent même pas clairement ce qu'ils font. Nous avons créé NOVA VISIO pour leur donner les mêmes armes que les grands : une image claire, un site qui travaille pour eux, et un accompagnement sans jargon.",
  "about.vision.label": "Vision",
  "about.vision.text": "Nous ne sommes pas une agence qui vous vend un site et disparaît. Chaque projet est un vrai partenariat : nous apprenons votre métier, nous comprenons vos clients, et nous créons des outils qui",
  "about.vision.highlight": "vous rapportent concrètement",
  "about.value.clarity": "Clarté",
  "about.value.clarity.desc": "On dit les choses simplement. Pas de jargon, pas de blabla.",
  "about.value.structure": "Structure",
  "about.value.structure.desc": "Chaque décision de design a une raison. Rien n'est là par hasard.",
  "about.value.simplicity": "Simplicité",
  "about.value.simplicity.desc": "Moins de superflu, plus d'impact. L'essentiel, bien exécuté.",
  "about.value.pedagogy": "Pédagogie",
  "about.value.pedagogy.desc": "On vous explique tout. Vous restez maître de votre image.",
  "about.mission.label": "Notre mission",
  "about.mission.text": "Identité visuelle, site web, supports de communication - nous ne faisons pas tout, mais ce que nous faisons, nous le faisons bien.",
  "about.mission.highlight": "Chaque projet repart avec des outils concrets",
  "about.mission.rest": ", pas des promesses en l'air.",
  "about.method.title": "Notre",
  "about.method.highlight": "méthode.",
  "about.method.text": "Un appel, un diagnostic, une proposition claire. Si on n'est pas la bonne solution, on vous le dit.",
  "about.method.cta": "Parlons de votre projet",
  "about.clients.badge": "Rayonnement international",
  "about.clients.title": "Nos clients à travers le",
  "about.clients.highlight": "monde.",
  "about.clients.subtitle": "Nous accompagnons des entrepreneurs et entreprises dans plusieurs pays",
  "about.skills.badge": "Expertise certifiée",
  "about.skills.title.1": "Compétences &",
  "about.skills.title.highlight": "certifications.",
  "about.skills.subtitle": "Des bases solides en design, marketing et IA pour créer des identités et des sites qui fonctionnent vraiment.",
  "about.skills.disclaimer": "Les certifications présentées ont été obtenues via des plateformes d'enseignement en ligne reconnues. Elles attestent d'un investissement continu dans la formation et ne constituent pas des diplômes académiques.",

  // ── Recommandation Page ──
  "recommandation.badge": "Programme de recommandation",
  "recommandation.title.1": "Recommandez.",
  "recommandation.title.highlight": "Gagnez 100 CHF.",
  "recommandation.subtitle.1": "Vous êtes satisfait de votre site ?",
  "recommandation.subtitle.2": "Faites-en profiter votre réseau. Pour chaque",
  "recommandation.subtitle.bold1": "nouveau client",
  "recommandation.subtitle.3": "on vous offre",
  "recommandation.subtitle.bold2": "100 CHF",
  "recommandation.steps.title": "3 étapes.",
  "recommandation.steps.highlight": "Zéro complication.",
  "recommandation.steps.subtitle": "Pas de formulaire compliqué.",
  "recommandation.steps.subtitle.bold": "conditions cachées",
  "recommandation.s1.title": "Vous recommandez",
  "recommandation.s1.desc": "Parlez de Nova Visio à un entrepreneur, artisan ou PME de votre réseau.",
  "recommandation.s2.title": "Il signe un projet",
  "recommandation.s2.desc": "Le nouveau client lance un projet de création de site web avec nous.",
  "recommandation.s3.title": "Vous recevez 100 CHF",
  "recommandation.s3.desc": "Dès la mise en ligne du site, on vous envoie votre récompense.",
  "recommandation.conditions.title": "Conditions",
  "recommandation.conditions.highlight": "simples.",
  "recommandation.conditions.subtitle.bold": "Tout est clair",
  "recommandation.conditions.subtitle": "dès le départ.",
  "recommandation.c1.label": "Montant",
  "recommandation.c1.value": "100 CHF par client signé.",
  "recommandation.c2.label": "Projets concernés",
  "recommandation.c2.value": "Création de site web (hors prestations ponctuelles mineures).",
  "recommandation.c3.label": "Versement",
  "recommandation.c3.value": "À la mise en ligne du site.",
  "recommandation.c4.label": "Modalités",
  "recommandation.c4.value": "Virement bancaire ou avoir sur une prochaine prestation.",
  "recommandation.c5.label": "Limite",
  "recommandation.c5.value": "Aucune. Recommandez autant de personnes que vous voulez.",
  "recommandation.cta.title": "Prêt à recommander ?",
  "recommandation.cta.subtitle.1": "Contactez-nous pour nous",
  "recommandation.cta.subtitle.bold": "transmettre le nom",
  "recommandation.cta.subtitle.2": "de la personne que vous recommandez.",
  "recommandation.cta.button": "Recommander quelqu'un →",

  // ── Blog Page ──
  "blog.page.title.1": "On partage ce qu'on",
  "blog.page.title.highlight": "sait.",
  "blog.page.subtitle": "Des articles concrets pour prendre de meilleures décisions sur votre site, votre image et votre présence en ligne.",
  "blog.tag": "Article",

  // ── Tarifs Page ──
  "tarifs.badge": "Nos tarifs",
  "tarifs.title.1": "Transparence totale.",
  "tarifs.title.highlight": "Des prix clairs. Point.",
  "tarifs.subtitle": "Vous savez ce que vous payez. Pas de frais cachés, pas de surprises.",
  "tarifs.reassurance.1": "Basé en Suisse, actif en France",
  "tarifs.reassurance.2": "Livraison en 7 à 14 jours",
  "tarifs.reassurance.3": "Appel découverte gratuit inclus",
  "tarifs.complementary": "+ Services complémentaires disponibles sur demande →",
  "tarifs.packs.title.1": "Tout en un ?",
  "tarifs.packs.title.highlight": "On a ce qu'il faut.",
  "tarifs.packs.subtitle": "Site + identité visuelle dans une seule offre. Moins de prestataires, plus de cohérence, et un",
  "tarifs.packs.subtitle.bold": "meilleur prix",
  "tarifs.cta.title.1": "Vous savez ce qu'il vous faut ?",
  "tarifs.cta.title.highlight": "On en parle.",
  "tarifs.cta.subtitle": "15 min d'appel gratuit. On fait le point et on vous dit honnêtement quelle offre correspond à votre situation.",
  "tarifs.cta.button": "Demander un devis gratuit",
  "tarifs.from": "dès",
  "tarifs.startProject": "Démarrer ce projet",
  "tarifs.vitrine.title": "Site vitrine",
  "tarifs.vitrine.subtitle": "Votre meilleur commercial",
  "tarifs.vitrine.badge": "Best-seller",
  "tarifs.vitrine.desc": "Un site qui dit clairement ce que vous faites et qui donne envie de vous contacter.",
  "tarifs.landing.title": "Landing page",
  "tarifs.landing.subtitle": "Un message, une action",
  "tarifs.landing.badge": "Starter",
  "tarifs.landing.desc": "Une seule page, un seul objectif : que vos visiteurs passent à l'action.",
  "tarifs.identity.title": "Identité visuelle",
  "tarifs.identity.subtitle": "Fini le logo bricolé",
  "tarifs.identity.badge": "Sur-mesure",
  "tarifs.identity.desc": "Logo, couleurs, typos, charte graphique - tout ce qu'il faut pour être reconnu au premier regard.",
  "tarifs.complementary.title": "Services complémentaires",
  "tarifs.complementary.badge": "+ Services complémentaires disponibles sur demande →",
  "tarifs.onQuote": "Sur devis",
  "tarifs.maintenance.needMore": "Besoin de plus de modifications ?",
  "tarifs.maintenance.needMore.desc": "Pour les projets avec des besoins réguliers en contenu ou en évolutions, le forfait",
  "tarifs.maintenance.needMore.price": "Actif à 149 CHF/mois",
  "tarifs.maintenance.needMore.desc2": "inclut 3h de modifs par mois, mise à jour de contenu et support prioritaire sous 24h.",
  "tarifs.maintenance.needMore.cta": "Me renseigner sur le forfait Actif",

  // ── Web Service Page ──
  "web.hero.badge": "Création de sites web & landing pages",
  "web.hero.title.1": "Votre site.",
  "web.hero.title.highlight": "Votre meilleur commercial.",
  "web.hero.subtitle": "Ce que vous faites, pourquoi vous faire confiance, comment travailler avec vous. Un site qui convertit. Point.",
  "web.hero.bullet1": "Des pages structurées qui expliquent clairement votre offre.",
  "web.hero.bullet2": "Un design qui rassure vos prospects - pas qui vous flatte.",
  "web.hero.bullet3": "Un site que vous pouvez modifier vous-même, sans appeler un développeur.",
  "web.hero.price": "Site vitrine dès 1'500 CHF - Livraison en 7 à 14 jours",
  "web.hero.cta.primary": "Réserver un appel gratuit →",
  "web.hero.cta.secondary": "Voir les tarifs →",
  "web.content.title": "Un beau site qui ne vend pas, c'est juste une jolie vitrine vide.",
  "web.content.p1.1": "Vos prospects arrivent sur votre site. En 3 secondes, ils décident de rester ou de partir. Ce qui fait la différence ? Pas les animations ou les effets - mais une structure qui dit clairement",
  "web.content.p1.bold": " qui vous êtes, ce que vous proposez, et pourquoi vous faire confiance",
  "web.content.p2": "Nous partons de votre activité, de vos vrais objectifs, et nous construisons un site où chaque page a un rôle précis : rassurer, guider, convaincre. Le design est au service du parcours, pas l'inverse. Résultat : vos visiteurs comprennent votre offre et passent à l'action - prise de contact, demande de devis, achat.",
  "web.content.cta": "Parler de votre projet",
  "web.maintenance.text": "Votre site est livré - mais votre présence en ligne ne s'arrête pas là. Mises à jour, modifs de contenu, suivi des performances : notre suivi mensuel à 89 CHF/mois prend le relais pour que votre site reste un outil qui bosse pour vous.",
  "web.showcase.title": "Livrés. En ligne.",
  "web.showcase.highlight": "Pour de vrai.",
  "web.showcase.subtitle": "Pas de maquettes Dribbble. De vrais projets, de vrais résultats.",
  "web.showcase.elearning": "Plateforme e-learning",
  "web.showcase.landing": "Landing page",
  "web.showcase.vitrine": "Site vitrine",
  "web.services.badge": "Nos expertises",
  "web.services.title": "Nos services de",
  "web.services.highlight": "création web.",
  "web.services.subtitle.1": "Tout ce qu'il faut pour transformer votre site",
  "web.services.subtitle.bold": "outil qui travaille",
  "web.services.subtitle.2": "pendant que vous dormez.",
  "web.offer.badge": "💎 Offres sur mesure",
  "web.offer.title": "Tout est inclus.",
  "web.offer.subtitle.1": "Deux formats. La même",
  "web.offer.subtitle.bold": "exigence",
  "web.steps.badge": "Processus de création",
  "web.steps.title": "Du brief au lancement.",
  "web.steps.highlight": "5 étapes.",
  "web.steps.subtitle.1": "Vous savez",
  "web.steps.subtitle.bold1": "exactement",
  "web.steps.subtitle.2": "où on en est.",
  "web.steps.subtitle.bold2": "chaque instant",
  "web.steps.duration": "Durée moyenne :",
  "web.steps.duration.value": "7 à 14 jours",
  "web.steps.start": "Démarrer",
  "web.faq.badge": "Questions fréquentes",
  "web.faq.title": "Vos questions.",
  "web.faq.highlight": "Nos réponses.",
  "web.faq.subtitle": "Tout ce qu'on nous demande avant de lancer un projet web.",
  "web.maintenance.title": "Et après la livraison ?",
  "web.maintenance.cta": "Découvrir le suivi mensuel",

  // ── Brand Service Page ──
  "brand.hero.badge": "Logo & identité visuelle sur mesure",
  "brand.hero.title.1": "Votre image.",
  "brand.hero.title.highlight": "Enfin à la hauteur.",
  "brand.hero.subtitle": "Logo, couleurs, typographies, charte graphique. Tout est créé de A à Z pour une marque reconnaissable, cohérente et utilisable partout.",
  "brand.hero.bullet1": "Un logo qui fonctionne en grand comme en petit, sur écran comme sur papier.",
  "brand.hero.bullet2": "Des couleurs et typos choisies pour vous - pas piochées au hasard.",
  "brand.hero.bullet3": "Des règles simples pour garder la même image partout, sans se prendre la tête.",
  "brand.hero.price": "Identité visuelle complète dès 900 CHF",
  "brand.hero.cta.primary": "Réserver un appel gratuit →",
  "brand.hero.cta.secondary": "Voir les tarifs →",
  "brand.content.title": "Un logo sur Canva, ce n'est pas une identité de marque.",
  "brand.content.p1": "Votre identité visuelle, c'est ce qui fait que vos clients vous reconnaissent en un coup d'œil - sur votre site, vos réseaux, vos cartes de visite. Un logo seul ne suffit pas. Il faut un système cohérent qui inspire confiance avant même que vous ayez dit un mot.",
  "brand.content.p2": "On crée des identités conçues pour durer et s'adapter facilement à tous vos supports. Pas de gadgets, pas de tendances éphémères - une image claire et professionnelle que vous pouvez déployer sans nous rappeler à chaque fois.",
  "brand.content.cta": "Discuter de votre projet",
  "brand.benefits.title": "L'impact.",
  "brand.benefits.highlight": "Immédiat.",
  "brand.benefits.subtitle.1": "Une identité qui",
  "brand.benefits.subtitle.bold": "simplifie votre quotidien",
  "brand.benefits.subtitle.2": "et change la",
  "brand.benefits.subtitle.bold2": "perception",
  "brand.benefits.subtitle.3": "de vos clients.",
  "brand.offer.title": "Tout est dedans.",
  "brand.offer.subtitle.1": "Une identité",
  "brand.offer.subtitle.bold": "unique et mémorable",
  "brand.offer.subtitle.2": ". Clé en main.",
  "brand.offer.badge": "SUR-MESURE",
  "brand.offer.for": "POUR : ARTISANS, PME, FREELANCES",
  "brand.offer.cardTitle": "Logo & identité",
  "brand.offer.cardHighlight": "visuelle complète",
  "brand.offer.cardDesc": "Une identité visuelle professionnelle pour être reconnu et inspirer",
  "brand.offer.cardDescBold": "confiance au premier regard",
  "brand.offer.included": "Ce qui est inclus",
  "brand.offer.cta": "Créer mon identité visuelle",
  "brand.details.badge": "Tout ce qui est inclus",
  "brand.details.title": "7 piliers.",
  "brand.details.highlight": "Rien de superflu.",
  "brand.details.subtitle": "Chaque élément a sa raison d'être. Que de l'utile.",
  "brand.details.bottom": "7 piliers",
  "brand.details.bottom2": "pour une identité complète",
  "brand.steps.badge": "Processus créatif",
  "brand.steps.title": "De l'idée au logo.",
  "brand.steps.highlight": "Étape par étape.",
  "brand.steps.subtitle.1": "Vous savez",
  "brand.steps.subtitle.bold1": "exactement",
  "brand.steps.subtitle.2": "où on en est.",
  "brand.steps.subtitle.bold2": "chaque étape",
  "brand.steps.duration": "Durée moyenne :",
  "brand.steps.duration.value": "3 à 6 semaines",
  "brand.steps.start": "Démarrer",
  "brand.complementary.badge": "Extensions disponibles",
  "brand.complementary.title": "Aller",
  "brand.complementary.highlight": "plus loin.",
  "brand.complementary.subtitle.1": "Exploitez votre identité",
  "brand.complementary.subtitle.bold1": "à fond",
  "brand.complementary.subtitle.2": "Sans jongler entre",
  "brand.complementary.subtitle.bold2": "5 outils",
  "brand.faq.badge": "Questions fréquentes",
  "brand.faq.title": "Vos questions.",
  "brand.faq.highlight": "Nos réponses.",
  "brand.faq.subtitle": "Tout ce qu'on nous demande avant de lancer une identité visuelle.",
  "brand.maintenance.text": "Votre identité est livrée - maintenant il faut la déployer partout sans se perdre. Notre suivi mensuel à 89 CHF/mois veille sur votre présence en ligne pendant que vous vous concentrez sur votre métier.",
  "finalcta.web.title.1": "Prêt ?",
  "finalcta.web.title.highlight": "On y va.",
  "finalcta.web.subtitle.bold1": "15 minutes",
  "finalcta.web.subtitle.1": "d'appel gratuit.",
  "finalcta.web.subtitle.bold2": "solution claire",
  "finalcta.web.subtitle.2": "On regarde ce qui bloque et on propose une",
  "finalcta.web.cta": "Réserver un appel gratuit",
  "finalcta.brand.title.1": "Votre image mérite",
  "finalcta.brand.title.highlight": "mieux.",
  "finalcta.brand.subtitle.bold1": "15 minutes",
  "finalcta.brand.subtitle.1": "d'appel gratuit.",
  "finalcta.brand.subtitle.bold2": "refonte vaut le coup",
  "finalcta.brand.subtitle.2": "On vous dit franchement si une",
  "finalcta.brand.cta": "Réserver un appel gratuit",

  // ── Packs Promo ──
  "packs.badge": "Offres combinées",
  "packs.title": "Tout-en-un.",
  "packs.highlight": "Sans compromis.",
  "packs.subtitle.bold1": "Identité visuelle + site web",
  "packs.subtitle": "Une seule offre, une",
  "packs.subtitle.bold2": "image cohérente",
  "packs.cta": "Découvrir tous nos packs",
  "packs.digital.title": "Pack Digital & Branding",
  "packs.digital.desc": "Logo + identité visuelle + site web complet. Un seul interlocuteur, une image cohérente dès le départ.",
  "packs.refonte.title": "Pack Refonte Globale",
  "packs.refonte.desc": "Audit complet + nouvelle identité + refonte de site. Pour remettre votre image à la hauteur.",

  // ── Mentions Légales ──
  "legal.title": "Mentions légales.",
  "legal.s1.title": "1. Éditeur du site",
  "legal.s1.intro": "Le site https://www.novavisio.ch est exploité par :",
  "legal.s1.name": "Nom / raison sociale :",
  "legal.s1.form": "Forme juridique :",
  "legal.s1.formValue": "Entreprise individuelle",
  "legal.s1.address": "Adresse postale :",
  "legal.s1.addressValue": "1226 Thônex - Suisse",
  "legal.s1.vat": "Numéro de TVA :",
  "legal.s1.vatValue": "Non assujetti à la TVA.",
  "legal.s2.title": "2. Direction de la publication",
  "legal.s2.text": "Responsable de la publication : le propriétaire de Nova Visio.",
  "legal.s3.title": "3. Hébergeur du site",
  "legal.s3.intro": "Le site est hébergé par :",
  "legal.s3.host": "Hébergeur :",
  "legal.s3.address": "Adresse :",
  "legal.s3.website": "Site web :",
  "legal.s4.title": "4. Propriété intellectuelle",
  "legal.s4.text": "Sauf mention contraire, l'ensemble des éléments présents sur ce site (textes, images, graphismes, logo, icônes, mise en page, etc.) est la propriété exclusive de Nova Visio ou fait l'objet d'une autorisation d'utilisation. Toute reproduction, représentation, adaptation ou diffusion, totale ou partielle, sur quelque support que ce soit, est interdite sans l'autorisation écrite préalable de Nova Visio.",
  "legal.s5.title": "5. Données personnelles",
  "legal.s5.p1": "Les informations recueillies via les formulaires (nom, prénom, adresse e‑mail, téléphone, message, etc.) sont utilisées uniquement pour répondre aux demandes et échanges commerciaux. Les données ne sont pas transmises à des tiers, sauf obligation légale ou prestataires techniques intervenant pour le fonctionnement du site (hébergement, outils de mesure d'audience, etc.).",
  "legal.s5.p2": "Vous pouvez demander l'accès, la rectification ou la suppression des informations vous concernant en écrivant à l'adresse e‑mail de contact indiquée ci‑dessus.",
  "legal.s6.title": "6. Limitation de responsabilité",
  "legal.s6.p1": "Les informations fournies sur ce site le sont à titre indicatif et général. Nova Visio s'efforce de les maintenir exactes et à jour, mais ne peut garantir leur exhaustivité ni l'absence d'erreurs, et décline toute responsabilité en cas d'utilisation qui en serait faite.",
  "legal.s6.p2": "Le site peut contenir des liens vers des sites tiers sur lesquels Nova Visio n'exerce aucun contrôle ; aucune responsabilité n'est engagée concernant leur contenu ou leurs pratiques.",
  "legal.s7.title": "7. Droit applicable et for juridique",
  "legal.s7.text": "Le présent site et les présentes mentions légales sont soumis au droit suisse. En cas de litige, et à défaut d'accord amiable, les tribunaux compétents sont ceux du canton de … (sous réserve de dispositions légales impératives).",

  // ── Cookie Consent ──
  "cookie.title": "Gérer le consentement",
  "cookie.text": "Nous utilisons des cookies pour stocker et accéder aux informations des appareils. Consentir nous permet de traiter des données comme le comportement de navigation.",
  "cookie.accept": "Accepter",
  "cookie.refuse": "Refuser",
  "cookie.preferences": "Préférences",
  "cookie.save": "Enregistrer",
  "cookie.back": "Retour",
  "cookie.essential": "Essentiels",
  "cookie.analytics": "Analytiques",
  "cookie.marketing": "Marketing",
  "cookie.close": "Fermer",

  // ── Not Found ──
  "notfound.title": "Page non trouvée",
  "notfound.subtitle": "Oups ! Cette page n'existe pas.",
  "notfound.cta": "Retour à l'accueil",

  // ── Validation ──
  "validation.firstName": "Prénom requis",
  "validation.lastName": "Nom requis",
  "validation.email": "Email invalide",
  "validation.message.min": "Minimum 10 caractères",
  "validation.message.max": "2000 caractères max",
  "validation.max50": "50 caractères max",
  "validation.max100": "100 caractères max",

  // ── Chatbot ──
  "chat.bubble.label": "Une question ?",
  "chat.bubble.ariaClose": "Fermer le chat",
  "chat.bubble.ariaOpen": "Parler avec Visio",
  "chat.header.title": "Parler avec Visio",
  "chat.header.subtitle": "Questions sur Nova Visio ou les offres ?",
  "chat.welcome": "Bonjour ! Je suis",
  "chat.welcome.name": "Visio",
  "chat.welcome.rest": ", l'assistant du studio.",
  "chat.welcome.question": "Comment puis-je vous aider ?",
  "chat.suggestion.1": "Quels services proposez-vous ?",
  "chat.suggestion.2": "Combien coûte un site web ?",
  "chat.suggestion.3": "Quelle est la durée d'un projet ?",
  "chat.input.placeholder": "Posez votre question...",
  "chat.error.prefix": "Désolé,",
  "chat.error.suffix": ". Veuillez réessayer ou contacter le studio directement via la page Contact.",
};

// ─── ENGLISH TRANSLATIONS ──────────────────────────────────────
const en: Record<string, string> = {
  // ── Navbar ──
  "nav.home": "Home",
  "nav.services": "Services",
  "nav.services.web": "Website",
  "nav.services.brand": "Logo & Brand Identity",
  "nav.pricing": "Pricing",
  "nav.referral": "Referral",
  "nav.blog": "Blog",
  "nav.about": "About",
  "nav.contact": "Contact",
  "nav.cta": "Let's talk about your project",

  // ── Hero ──
  "hero.badge": "Made in Switzerland · Craftspeople, freelancers & SMEs",
  "hero.title.line1": "Your talent deserves",
  "hero.title.highlight": "to be seen.",
  "hero.subtitle": "Showcase website, landing page, brand identity.",
  "hero.subtitle2": "The tools to be seen, understood",
  "hero.subtitle3": "and contacted. From",
  "hero.subtitle.price": "900 CHF",
  "hero.cta.primary": "Book a free call",
  "hero.cta.secondary": "Explore our services",

  // ── Services Section (Home) ──
  "services.title.line1": "Two expertises.",
  "services.title.highlight": "One single goal.",
  "services.subtitle.1": "Be seen",
  "services.subtitle.2": "Be understood",
  "services.subtitle.3": "Be chosen",
  "services.web.title": "Showcase website and landing page",
  "services.web.description": "Your prospects land, understand your offer in 5 seconds and reach out. That's what a great website does.",
  "services.web.cta": "Explore our web projects →",
  "services.web.price": "from 900 CHF",
  "services.brand.title": "Brand identity & logo",
  "services.brand.description": "No more DIY logos. A real identity that sets you apart and works across every touchpoint.",
  "services.brand.cta": "See our brand identities →",
  "services.brand.price": "from 900 CHF",
  "services.badge": "FOR: CRAFTSPEOPLE, SMES, FREELANCERS, STARTUPS",
  "services.web.b1": "Build credibility",
  "services.web.b1h": "from the very first second",
  "services.web.b2": "Turn visitors",
  "services.web.b2h": "into qualified leads",
  "services.web.b3": "Present your services",
  "services.web.b3h": "with clarity and impact",
  "services.web.b4": "Rank on Google",
  "services.web.b4h": "with built-in SEO",
  "services.web.b5": "A fast, smooth website",
  "services.web.b5h": "on mobile and desktop",
  "services.brand.b1": "Be recognised",
  "services.brand.b1h": "at first glance",
  "services.brand.b2": "Inspire trust",
  "services.brand.b2h": "before you even speak",
  "services.brand.b3": "A consistent image",
  "services.brand.b3h": "across all your touchpoints",
  "services.brand.b4": "Stand out",
  "services.brand.b4h": "from your competitors",
  "services.brand.b5": "A professional logo",
  "services.brand.b5h": "ready for any format",
  "services.brand.b6": "Brand guidelines",
  "services.brand.b6h": "that are easy to follow",

  // ── Maintenance Section (Home) ──
  "maintenance.badge": "🔄 Ongoing support",
  "maintenance.title.1": "Delivered.",
  "maintenance.title.2": "Then supported.",
  "maintenance.subtitle": "performance, updates.",
  "maintenance.subtitle.bold1": "Updates",
  "maintenance.subtitle.bold2": "working for you",
  "maintenance.card.bestseller": "⭐ Best-seller",
  "maintenance.card.title": "Support & Maintenance",
  "maintenance.card.subtitle": "Your site stays performant — with zero effort on your end.",
  "maintenance.card.from": "from",
  "maintenance.card.price": "89 CHF/month",
  "maintenance.card.nocommit": "No commitment — cancel anytime",
  "maintenance.card.f1": "Hosting & domain name",
  "maintenance.card.f1h": "managed",
  "maintenance.card.f2": "Technical updates",
  "maintenance.card.f2h": "& security",
  "maintenance.card.f3": "Automatic backups",
  "maintenance.card.f3h": "weekly",
  "maintenance.card.f4": "1 hour of content",
  "maintenance.card.f4h": "updates per month",
  "maintenance.card.f5": "Monthly performance report",
  "maintenance.card.f5h": "(visits, leads)",
  "maintenance.card.f6": "Responsive support",
  "maintenance.card.f6h": "within 48 hours",
  "maintenance.card.cta": "Activate support",
  "maintenance.card.included": "Automatically included at the end of every project.",

  // ── Benefits Section (Home) ──
  "benefits.title.1": "What it changes.",
  "benefits.title.2": "Concretely.",
  "benefits.subtitle": "When your image and your website",
  "benefits.subtitle2": "finally do the heavy lifting.",
  "benefits.b1.text": "Your clients understand ",
  "benefits.b1.highlight": "in seconds",
  "benefits.b1.rest": " what you do — no more repeating yourself.",
  "benefits.b2.text": "You have a ",
  "benefits.b2.highlight": "professional, consistent image",
  "benefits.b2.rest": " across all your channels, without spending your evenings on it.",
  "benefits.b3.text": "You ",
  "benefits.b3.highlight": "attract the right clients",
  "benefits.b3.rest": " — those who appreciate your value and don't haggle on price.",
  "benefits.b4.text": "Your ",
  "benefits.b4.highlight": "digital mental load drops",
  "benefits.b4.rest": ": everything's in place, so you can focus on your craft.",

  // ── Why Us Section ──
  "whyus.badge": "What sets us apart",
  "whyus.title.1": "NOVA VISIO.",
  "whyus.title.highlight": "The difference.",
  "whyus.r1.title": "Zero jargon",
  "whyus.r1.desc": "We speak like humans. No \"UX synergies\" or \"digital paradigms\".",
  "whyus.r2.title": "Genuine\nsupport",
  "whyus.r2.desc": "We don't disappear after delivery. We're here as long as you need us.",
  "whyus.r3.title": "Quality > quantity",
  "whyus.r3.desc": "We take on few projects at a time. Each one gets our full attention.",
  "whyus.r4.title": "Results,\nnot promises",
  "whyus.r4.desc": "We don't sell dreams. We build tools that actually work for you.",

  // ── Steps Section (Home) ──
  "steps.title": "5 steps.",
  "steps.title.highlight": "Zero guesswork.",
  "steps.subtitle.bold1": "simple",
  "steps.subtitle.bold2": "transparent",
  "steps.subtitle.rest": "from start to finish.",
  "steps.s1.title": "We talk",
  "steps.s1.subtitle": "15 min",
  "steps.s1.desc": "A free call to understand your business, your goals, and what's holding you back.",
  "steps.s2.title": "We assess",
  "steps.s2.subtitle": "your situation",
  "steps.s2.desc": "We review what's in place — site, image, messaging — and pinpoint what needs to change.",
  "steps.s3.title": "We build",
  "steps.s3.subtitle": "the foundations",
  "steps.s3.desc": "Positioning, visual identity, message structure. Solid groundwork before design.",
  "steps.s4.title": "We create",
  "steps.s4.subtitle": "your site",
  "steps.s4.desc": "Custom design, conversion-driven pages, seamless experience on every screen.",
  "steps.s5.title": "We launch",
  "steps.s5.subtitle": "& follow up",
  "steps.s5.desc": "Go live, quick training, and monthly support to keep your site effective.",
  "steps.bottom": "A transparent, collaborative process",

  // ── CTA Section (Home) ──
  "cta.title.1": "15 minutes.",
  "cta.title.highlight": "No strings attached.",
  "cta.subtitle.1": "We'll review",
  "cta.subtitle.bold1": "your situation",
  "cta.subtitle.2": "and tell you",
  "cta.subtitle.bold2": "honestly",
  "cta.subtitle.3": "if we can help.",
  "cta.primary": "Book a free call →",
  "cta.secondary": "See our pricing →",

  // ── Referral CTA ──
  "referral.title.1": "Refer Nova Visio.",
  "referral.title.highlight": "Earn CHF 100.",
  "referral.subtitle.1": "Know someone launching a business?",
  "referral.subtitle.bold1": "Tell them about us",
  "referral.subtitle.2": "If they sign a website project, you receive",
  "referral.subtitle.bold2": "CHF 100",
  "referral.cta": "Discover the programme →",

  // ── Blog Section (Home) ──
  "blog.title.1": "We share. We",
  "blog.title.highlight": "enlighten.",
  "blog.subtitle.bold1": "practical",
  "blog.subtitle.1": "articles about your site,",
  "blog.subtitle.bold2": "online presence",
  "blog.subtitle.2": "your image and your",
  "blog.readArticle": "Read article",
  "blog.viewAll": "View all articles",

  // ── Footer ──
  "footer.rights": "All rights reserved.",

  // ── Contact Page ──
  "contact.title.1": "Let's talk.",
  "contact.title.highlight": "15 minutes.",
  "contact.subtitle.bold1": "your situation",
  "contact.subtitle.1": "We'll review",
  "contact.subtitle.2": "No sales pitch.",
  "contact.subtitle.bold2": "honest conversation",
  "contact.subtitle.3": "Just an",
  "contact.form.firstName": "First name",
  "contact.form.firstName.placeholder": "Your first name",
  "contact.form.lastName": "Last name",
  "contact.form.lastName.placeholder": "Your last name",
  "contact.form.email": "Email",
  "contact.form.email.placeholder": "your@email.com",
  "contact.form.projectType": "Project type",
  "contact.form.projectType.placeholder": "Select a project type",
  "contact.form.projectType.call": "Free discovery call (15 min)",
  "contact.form.projectType.website": "Showcase website",
  "contact.form.projectType.landing": "Landing page",
  "contact.form.projectType.brand": "Brand identity & logo",
  "contact.form.projectType.packDigital": "Digital & Branding Pack",
  "contact.form.projectType.packRefonte": "Complete Rebrand Pack",
  "contact.form.projectType.maintenance": "Support & Maintenance",
  "contact.form.projectType.other": "Other / Question",
  "contact.form.message": "Message",
  "contact.form.message.placeholder": "Describe your project and goals...",
  "contact.form.submit": "Send my enquiry",
  "contact.form.submitting": "Sending...",
  "contact.form.reassurance": "✓ Reply within 24h   ✓ No commitment   ✓ Call in English or French",
  "contact.form.success.title": "Message sent!",
  "contact.form.success.desc": "We'll get back to you within 24 to 48 hours.",
  "contact.form.error.title": "Error",
  "contact.form.error.desc": "Something went wrong. Please try again.",
  "contact.form.validation.title": "Validation error",
  "contact.form.validation.desc": "Please fix the errors in the form.",
  "contact.whatNext.fast.title": "Fast response",
  "contact.whatNext.fast.desc": "We'll get back to you within 24 to 48 hours.",
  "contact.whatNext.noPressure.title": "No pressure",
  "contact.whatNext.noPressure.item1": "Constructive discussion",
  "contact.whatNext.noPressure.item2": "Tailored solutions",
  "contact.booking.title": "Or book a",
  "contact.booking.highlight": "time slot",

  // ── About Page ──
  "about.title": "Who we",
  "about.title.highlight": "are.",
  "about.subtitle": "Too many entrepreneurs deserve better",
  "about.subtitle2": "than a website built on a generic template.",
  "about.trigger.label": "The spark",
  "about.trigger.p1": "It all started from a frustrating observation: craftspeople, freelancers, and small businesses with solid offerings — but an online presence that didn't do them justice.",
  "about.trigger.p2": "Cobbled-together template websites, logos made \"by a friend\", pages that didn't even clearly explain what they do. We created NOVA VISIO to give them the same tools as the big players: a clear image, a website that works for them, and support without jargon.",
  "about.vision.label": "Vision",
  "about.vision.text": "We're not an agency that sells you a site and vanishes. Every project is a genuine partnership: we learn your business, understand your clients, and create tools that",
  "about.vision.highlight": "deliver real results",
  "about.value.clarity": "Clarity",
  "about.value.clarity.desc": "We say things simply. No jargon, no fluff.",
  "about.value.structure": "Structure",
  "about.value.structure.desc": "Every design decision has a reason. Nothing is there by accident.",
  "about.value.simplicity": "Simplicity",
  "about.value.simplicity.desc": "Less noise, more impact. The essentials, done well.",
  "about.value.pedagogy": "Guidance",
  "about.value.pedagogy.desc": "We explain everything. You stay in control of your image.",
  "about.mission.label": "Our mission",
  "about.mission.text": "Visual identity, website, marketing materials — we don't do everything, but what we do, we do it well.",
  "about.mission.highlight": "Every project leaves with concrete tools",
  "about.mission.rest": ", not empty promises.",
  "about.method.title": "Our",
  "about.method.highlight": "approach.",
  "about.method.text": "A call, an assessment, a clear proposal. If we're not the right fit, we'll tell you.",
  "about.method.cta": "Let's talk about your project",
  "about.clients.badge": "International reach",
  "about.clients.title": "Our clients around the",
  "about.clients.highlight": "world.",
  "about.clients.subtitle": "We work with entrepreneurs and businesses across multiple countries",
  "about.skills.badge": "Certified expertise",
  "about.skills.title.1": "Skills &",
  "about.skills.title.highlight": "certifications.",
  "about.skills.subtitle": "Solid foundations in design, marketing and AI to create identities and websites that actually work.",
  "about.skills.disclaimer": "The certifications listed were obtained through recognised online learning platforms. They reflect an ongoing commitment to professional development and are not academic degrees.",

  // ── Recommandation Page ──
  "recommandation.badge": "Referral programme",
  "recommandation.title.1": "Refer us.",
  "recommandation.title.highlight": "Earn CHF 100.",
  "recommandation.subtitle.1": "Happy with your website?",
  "recommandation.subtitle.2": "Spread the word. For every",
  "recommandation.subtitle.bold1": "new client",
  "recommandation.subtitle.3": "we give you",
  "recommandation.subtitle.bold2": "CHF 100",
  "recommandation.steps.title": "3 steps.",
  "recommandation.steps.highlight": "Zero hassle.",
  "recommandation.steps.subtitle": "No complicated forms.",
  "recommandation.steps.subtitle.bold": "hidden conditions",
  "recommandation.s1.title": "You refer",
  "recommandation.s1.desc": "Tell an entrepreneur, craftsperson or SME in your network about Nova Visio.",
  "recommandation.s2.title": "They sign a project",
  "recommandation.s2.desc": "The new client starts a website project with us.",
  "recommandation.s3.title": "You receive CHF 100",
  "recommandation.s3.desc": "Once the site goes live, we send you your reward.",
  "recommandation.conditions.title": "Straightforward",
  "recommandation.conditions.highlight": "terms.",
  "recommandation.conditions.subtitle.bold": "Everything is clear",
  "recommandation.conditions.subtitle": "from the start.",
  "recommandation.c1.label": "Amount",
  "recommandation.c1.value": "CHF 100 per signed client.",
  "recommandation.c2.label": "Eligible projects",
  "recommandation.c2.value": "Website creation (excluding minor one-off services).",
  "recommandation.c3.label": "Payment",
  "recommandation.c3.value": "Upon site launch.",
  "recommandation.c4.label": "Method",
  "recommandation.c4.value": "Bank transfer or credit towards a future project.",
  "recommandation.c5.label": "Limit",
  "recommandation.c5.value": "None. Refer as many people as you'd like.",
  "recommandation.cta.title": "Ready to refer?",
  "recommandation.cta.subtitle.1": "Get in touch to",
  "recommandation.cta.subtitle.bold": "share the name",
  "recommandation.cta.subtitle.2": "of the person you're referring.",
  "recommandation.cta.button": "Refer someone →",

  // ── Blog Page ──
  "blog.page.title.1": "We share what we",
  "blog.page.title.highlight": "know.",
  "blog.page.subtitle": "Practical articles to help you make better decisions about your website, your image, and your online presence.",
  "blog.tag": "Article",

  // ── Tarifs Page ──
  "tarifs.badge": "Our pricing",
  "tarifs.title.1": "Total transparency.",
  "tarifs.title.highlight": "Clear pricing. Period.",
  "tarifs.subtitle": "You know what you're paying for. No hidden fees, no surprises.",
  "tarifs.reassurance.1": "Based in Switzerland, active in France",
  "tarifs.reassurance.2": "Delivery in 7 to 14 days",
  "tarifs.reassurance.3": "Free discovery call included",
  "tarifs.complementary": "+ Additional services available on request →",
  "tarifs.packs.title.1": "Want it all?",
  "tarifs.packs.title.highlight": "We've got you covered.",
  "tarifs.packs.subtitle": "Website + brand identity in a single offer. Fewer providers, more consistency, and a",
  "tarifs.packs.subtitle.bold": "better price",
  "tarifs.cta.title.1": "Know what you need?",
  "tarifs.cta.title.highlight": "Let's talk.",
  "tarifs.cta.subtitle": "15-minute free call. We'll assess your needs and honestly recommend the right package for you.",
  "tarifs.cta.button": "Request a free quote",
  "tarifs.from": "from",
  "tarifs.startProject": "Start this project",
  "tarifs.vitrine.title": "Showcase website",
  "tarifs.vitrine.subtitle": "Your best salesperson",
  "tarifs.vitrine.badge": "Best-seller",
  "tarifs.vitrine.desc": "A website that clearly tells people what you do and makes them want to reach out.",
  "tarifs.landing.title": "Landing page",
  "tarifs.landing.subtitle": "One message, one action",
  "tarifs.landing.badge": "Starter",
  "tarifs.landing.desc": "A single page with one goal: get your visitors to take action.",
  "tarifs.identity.title": "Brand identity",
  "tarifs.identity.subtitle": "No more DIY logos",
  "tarifs.identity.badge": "Bespoke",
  "tarifs.identity.desc": "Logo, colours, fonts, brand guidelines — everything you need to be recognised at first glance.",
  "tarifs.complementary.title": "Additional services",
  "tarifs.complementary.badge": "+ Additional services available on request →",
  "tarifs.onQuote": "On request",
  "tarifs.maintenance.needMore": "Need more updates?",
  "tarifs.maintenance.needMore.desc": "For projects with regular content or development needs, the",
  "tarifs.maintenance.needMore.price": "Active plan at 149 CHF/month",
  "tarifs.maintenance.needMore.desc2": "includes 3 hours of updates per month, content changes and priority support within 24 hours.",
  "tarifs.maintenance.needMore.cta": "Learn more about the Active plan",

  // ── Web Service Page ──
  "web.hero.badge": "Website & landing page creation",
  "web.hero.title.1": "Your website.",
  "web.hero.title.highlight": "Your best salesperson.",
  "web.hero.subtitle": "What you do, why they should trust you, how to work with you. A site that converts. Simple.",
  "web.hero.bullet1": "Structured pages that clearly explain your offering.",
  "web.hero.bullet2": "A design that reassures your prospects — not just flatters you.",
  "web.hero.bullet3": "A site you can update yourself, without calling a developer.",
  "web.hero.price": "Showcase website from 1,500 CHF — Delivery in 7 to 14 days",
  "web.hero.cta.primary": "Book a free call →",
  "web.hero.cta.secondary": "See pricing →",
  "web.content.title": "A beautiful site that doesn't sell is just a pretty empty shopfront.",
  "web.content.p1.1": "Your prospects land on your site. In 3 seconds, they decide to stay or leave. What makes the difference? Not animations or effects — but a structure that clearly says",
  "web.content.p1.bold": " who you are, what you offer, and why they should trust you",
  "web.content.p2": "We start from your business, your real objectives, and we build a site where every page has a clear purpose: reassure, guide, convince. Design serves the journey, not the other way around. Result: your visitors understand your offer and take action — enquiry, quote request, purchase.",
  "web.content.cta": "Talk about your project",
  "web.maintenance.text": "Your site is delivered — but your online presence doesn't stop there. Updates, content changes, performance tracking: our monthly support at 89 CHF/month takes over so your site keeps working for you.",
  "web.showcase.title": "Delivered. Live.",
  "web.showcase.highlight": "For real.",
  "web.showcase.subtitle": "No Dribbble mockups. Real projects, real results.",
  "web.showcase.elearning": "E-learning platform",
  "web.showcase.landing": "Landing page",
  "web.showcase.vitrine": "Showcase website",
  "web.services.badge": "Our expertise",
  "web.services.title": "Our web",
  "web.services.highlight": "creation services.",
  "web.services.subtitle.1": "Everything you need to turn your website into a",
  "web.services.subtitle.bold": "tool that works",
  "web.services.subtitle.2": "while you sleep.",
  "web.offer.badge": "💎 Bespoke packages",
  "web.offer.title": "Everything's included.",
  "web.offer.subtitle.1": "Two formats. The same",
  "web.offer.subtitle.bold": "standards",
  "web.steps.badge": "Creation process",
  "web.steps.title": "From brief to launch.",
  "web.steps.highlight": "5 steps.",
  "web.steps.subtitle.1": "You know",
  "web.steps.subtitle.bold1": "exactly",
  "web.steps.subtitle.2": "where things stand.",
  "web.steps.subtitle.bold2": "every step",
  "web.steps.duration": "Average timeline:",
  "web.steps.duration.value": "7 to 14 days",
  "web.steps.start": "Get started",
  "web.faq.badge": "Frequently asked questions",
  "web.faq.title": "Your questions.",
  "web.faq.highlight": "Our answers.",
  "web.faq.subtitle": "Everything we get asked before starting a web project.",
  "web.maintenance.title": "What happens after delivery?",
  "web.maintenance.cta": "Discover monthly support",

  // ── Brand Service Page ──
  "brand.hero.badge": "Bespoke logo & brand identity",
  "brand.hero.title.1": "Your image.",
  "brand.hero.title.highlight": "Finally worthy of your business.",
  "brand.hero.subtitle": "Logo, colours, typography, brand guidelines. Everything built from scratch for a recognisable, consistent brand you can use everywhere.",
  "brand.hero.bullet1": "A logo that works large or small, on screen or in print.",
  "brand.hero.bullet2": "Colours and fonts chosen specifically for you — not picked at random.",
  "brand.hero.bullet3": "Simple rules to maintain a consistent image everywhere, hassle-free.",
  "brand.hero.price": "Complete brand identity from 900 CHF",
  "brand.hero.cta.primary": "Book a free call →",
  "brand.hero.cta.secondary": "See pricing →",
  "brand.content.title": "A Canva logo is not a brand identity.",
  "brand.content.p1": "Your visual identity is what makes clients recognise you at a glance — on your website, social media, and business cards. A logo alone isn't enough. You need a cohesive system that builds trust before you've said a word.",
  "brand.content.p2": "We create identities built to last and easily adapt to all your touchpoints. No gimmicks, no fleeting trends — a clear, professional image you can roll out without calling us every time.",
  "brand.content.cta": "Discuss your project",
  "brand.benefits.title": "The impact.",
  "brand.benefits.highlight": "Immediate.",
  "brand.benefits.subtitle.1": "An identity that",
  "brand.benefits.subtitle.bold": "simplifies your day-to-day",
  "brand.benefits.subtitle.2": "and changes how",
  "brand.benefits.subtitle.bold2": "clients perceive",
  "brand.benefits.subtitle.3": "you.",
  "brand.offer.title": "It's all included.",
  "brand.offer.subtitle.1": "A",
  "brand.offer.subtitle.bold": "unique and memorable",
  "brand.offer.subtitle.2": " identity. Turnkey.",
  "brand.offer.badge": "BESPOKE",
  "brand.offer.for": "FOR: CRAFTSPEOPLE, SMES, FREELANCERS",
  "brand.offer.cardTitle": "Logo & complete",
  "brand.offer.cardHighlight": "brand identity",
  "brand.offer.cardDesc": "A professional visual identity to be recognised and inspire",
  "brand.offer.cardDescBold": "trust at first sight",
  "brand.offer.included": "What's included",
  "brand.offer.cta": "Create my brand identity",
  "brand.details.badge": "Everything that's included",
  "brand.details.title": "7 pillars.",
  "brand.details.highlight": "Nothing superfluous.",
  "brand.details.subtitle": "Every element has a purpose. Only what's useful.",
  "brand.details.bottom": "7 pillars",
  "brand.details.bottom2": "for a complete identity",
  "brand.steps.badge": "Creative process",
  "brand.steps.title": "From idea to logo.",
  "brand.steps.highlight": "Step by step.",
  "brand.steps.subtitle.1": "You know",
  "brand.steps.subtitle.bold1": "exactly",
  "brand.steps.subtitle.2": "where things stand.",
  "brand.steps.subtitle.bold2": "every step",
  "brand.steps.duration": "Average timeline:",
  "brand.steps.duration.value": "3 to 6 weeks",
  "brand.steps.start": "Get started",
  "brand.complementary.badge": "Available extensions",
  "brand.complementary.title": "Go",
  "brand.complementary.highlight": "further.",
  "brand.complementary.subtitle.1": "Make the most of your identity",
  "brand.complementary.subtitle.bold1": "fully",
  "brand.complementary.subtitle.2": "Without juggling",
  "brand.complementary.subtitle.bold2": "5 different tools",
  "brand.faq.badge": "Frequently asked questions",
  "brand.faq.title": "Your questions.",
  "brand.faq.highlight": "Our answers.",
  "brand.faq.subtitle": "Everything we get asked before starting a brand identity project.",
  "brand.maintenance.text": "Your identity is delivered — now it needs to be deployed everywhere without losing consistency. Our monthly support at 89 CHF/month takes care of your online presence while you focus on your craft.",
  "finalcta.web.title.1": "Ready?",
  "finalcta.web.title.highlight": "Let's go.",
  "finalcta.web.subtitle.bold1": "15 minutes",
  "finalcta.web.subtitle.1": "free call.",
  "finalcta.web.subtitle.bold2": "clear solution",
  "finalcta.web.subtitle.2": "We'll review what's holding you back and propose a",
  "finalcta.web.cta": "Book a free call",
  "finalcta.brand.title.1": "Your image deserves",
  "finalcta.brand.title.highlight": "better.",
  "finalcta.brand.subtitle.bold1": "15 minutes",
  "finalcta.brand.subtitle.1": "free call.",
  "finalcta.brand.subtitle.bold2": "rebrand is worth it",
  "finalcta.brand.subtitle.2": "We'll honestly tell you whether a",
  "finalcta.brand.cta": "Book a free call",

  // ── Packs Promo ──
  "packs.badge": "Combined packages",
  "packs.title": "All-in-one.",
  "packs.highlight": "No compromises.",
  "packs.subtitle.bold1": "Brand identity + website",
  "packs.subtitle": "A single package, one",
  "packs.subtitle.bold2": "cohesive image",
  "packs.cta": "Discover all our packages",
  "packs.digital.title": "Digital & Branding Pack",
  "packs.digital.desc": "Logo + brand identity + full website. One point of contact, a cohesive image from day one.",
  "packs.refonte.title": "Complete Rebrand Pack",
  "packs.refonte.desc": "Full audit + new identity + website redesign. To bring your image up to standard.",

  // ── Mentions Légales ──
  "legal.title": "Legal notice.",
  "legal.s1.title": "1. Website publisher",
  "legal.s1.intro": "The website https://www.novavisio.ch is operated by:",
  "legal.s1.name": "Name / business name:",
  "legal.s1.form": "Legal form:",
  "legal.s1.formValue": "Sole proprietorship",
  "legal.s1.address": "Postal address:",
  "legal.s1.addressValue": "1226 Thônex - Switzerland",
  "legal.s1.vat": "VAT number:",
  "legal.s1.vatValue": "Not subject to VAT.",
  "legal.s2.title": "2. Publication director",
  "legal.s2.text": "Responsible for publication: the owner of Nova Visio.",
  "legal.s3.title": "3. Website hosting",
  "legal.s3.intro": "The website is hosted by:",
  "legal.s3.host": "Host:",
  "legal.s3.address": "Address:",
  "legal.s3.website": "Website:",
  "legal.s4.title": "4. Intellectual property",
  "legal.s4.text": "Unless otherwise stated, all elements on this website (text, images, graphics, logo, icons, layout, etc.) are the exclusive property of Nova Visio or are used with authorisation. Any reproduction, representation, adaptation or distribution, in whole or in part, on any medium whatsoever, is prohibited without the prior written consent of Nova Visio.",
  "legal.s5.title": "5. Personal data",
  "legal.s5.p1": "Information collected through forms (name, first name, email address, phone number, message, etc.) is used solely to respond to enquiries and for commercial correspondence. Data is not shared with third parties, except where legally required or with technical service providers involved in operating the website (hosting, analytics tools, etc.).",
  "legal.s5.p2": "You may request access to, correction of, or deletion of your personal information by writing to the contact email address provided above.",
  "legal.s6.title": "6. Limitation of liability",
  "legal.s6.p1": "The information provided on this website is for general informational purposes. Nova Visio strives to keep it accurate and up to date but cannot guarantee its completeness or the absence of errors, and disclaims any liability arising from its use.",
  "legal.s6.p2": "This website may contain links to third-party websites over which Nova Visio has no control; no liability is accepted regarding their content or practices.",
  "legal.s7.title": "7. Applicable law and jurisdiction",
  "legal.s7.text": "This website and these legal notices are governed by Swiss law. In the event of a dispute, and failing an amicable agreement, the competent courts shall be those of the relevant canton (subject to mandatory legal provisions).",

  // ── Cookie Consent ──
  "cookie.title": "Manage consent",
  "cookie.text": "We use cookies to store and access device information. Consenting allows us to process data such as browsing behaviour.",
  "cookie.accept": "Accept",
  "cookie.refuse": "Refuse",
  "cookie.preferences": "Preferences",
  "cookie.save": "Save",
  "cookie.back": "Back",
  "cookie.essential": "Essential",
  "cookie.analytics": "Analytics",
  "cookie.marketing": "Marketing",
  "cookie.close": "Close",

  // ── Not Found ──
  "notfound.title": "Page not found",
  "notfound.subtitle": "Oops! This page doesn't exist.",
  "notfound.cta": "Back to home",

  // ── Validation ──
  "validation.firstName": "First name required",
  "validation.lastName": "Last name required",
  "validation.email": "Invalid email",
  "validation.message.min": "Minimum 10 characters",
  "validation.message.max": "2,000 characters max",
  "validation.max50": "50 characters max",
  "validation.max100": "100 characters max",

  // ── Chatbot ──
  "chat.bubble.label": "Any questions?",
  "chat.bubble.ariaClose": "Close chat",
  "chat.bubble.ariaOpen": "Chat with Visio",
  "chat.header.title": "Chat with Visio",
  "chat.header.subtitle": "Questions about Nova Visio or our services?",
  "chat.welcome": "Hello! I'm",
  "chat.welcome.name": "Visio",
  "chat.welcome.rest": ", the studio's assistant.",
  "chat.welcome.question": "How can I help you?",
  "chat.suggestion.1": "What services do you offer?",
  "chat.suggestion.2": "How much does a website cost?",
  "chat.suggestion.3": "How long does a project take?",
  "chat.input.placeholder": "Ask your question...",
  "chat.error.prefix": "Sorry,",
  "chat.error.suffix": ". Please try again or contact the studio directly via the Contact page.",
};
